Invoice decimal precision
irontec/ivozprovider pull request #1639
Opened 2021-09-21 11:42 UTC by mmadariaga

Use two decimals instead of four in invoice tax amount

#### Type Of Change 
- [ ] Small bug fix
- [X] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [X] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [X] Commits are split per component (schema, web/admin, kamusers, agis, ..)
- [X] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX)

2021-09-22 07:59 UTC, Kaian approved these changes

2021-09-22 08:11 UTC, ironArt3mis commented
Rebase completed.

2021-09-23 16:20 UTC, cruzccl requested changes

2021-09-23 16:20 UTC, cruzccl commented on library/Ivoz/Provider/Domain/Service/Invoice/Generator.php
>          $totalWithTaxex = ceil(($totalTaxex + $total)*100)/100;
```suggestion
        $totalWithTaxex = $totalTaxex + $total;
```

2021-09-23 16:29 UTC, cruzccl approved these changes

2021-09-24 07:58 UTC, merged