vPBX Users Location support
irontec/ivozprovider pull request #1746
Opened 2022-03-22 13:48 UTC by Kaian

#### Type Of Change 
- [ ] Small bug fix
- [X] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [X] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [X] Commits are split per component (schema, web/admin, kamusers, agis, ..)
- [X] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 

#### Description
Adds a new entity that allows vPBX users to be grouped based on where they are working at.
Locations have no internal usage yet but they're pre-requisite to future implementations.

This is the upport for halliday of #1716

#### Additional information

2022-03-24 16:10 UTC, ironArt3mis commented
Rebase completed.

2022-03-30 09:45 UTC, mmadariaga requested changes

2022-03-30 09:45 UTC, mmadariaga commented on schema/DoctrineMigrations/Version20220322110232.php
> +        $this->addSql('CREATE INDEX IDX_D5428AED5E9E89CB ON Users (location)');
Register this entity in PublicEntities in order to use API ACLs

2022-03-30 09:45 UTC, mmadariaga commented on web/client/src/entities/Location/Location.tsx
> +    toStr: (row: any) => row.name,
toStr: (row: any) => row?.name || '' => would be better

2022-03-31 06:46 UTC, Kaian commented
Updated with requested changes

2022-03-31 07:21 UTC, mmadariaga approved these changes

2022-03-31 07:21 UTC, merged