Provider 378 send fax from new client portal
irontec/ivozprovider pull request #1854
Opened 2022-07-08 09:28 UTC by mmadariaga

#### Type Of Change 
- [ ] Small bug fix
- [ ] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [ ] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [ ] Commits are split per component (schema, web/admin, kamusers, agis, ..)
- [ ] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 

#### Description

#### Additional information

2022-07-11 09:54 UTC, ironBatista approved these changes

2022-07-12 06:17 UTC, Kaian commented on web/rest/client/features/provider/faxesInOut/postFaxesInOut.feature
> +          "src": "34688888888",
`src` field should also be readonly for Faxes Out, as it's assigned from configured outgoingDDI field

2022-07-12 06:18 UTC, Kaian requested changes

2022-07-12 06:18 UTC, Kaian commented on web/rest/client/config/api/raw/provider.yml
> +          readOnly: true
`src` should also be readonly for Outgoing faxes

2022-07-14 07:14 UTC, Kaian approved these changes

2022-07-14 07:17 UTC, merged