Provider 416 revisar deprecation warning
irontec/ivozprovider pull request #1875
Opened 2022-08-02 15:44 UTC by ironBatista

#### Type Of Change 
- [ ] Small bug fix
- [X] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [X] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [ ] Commits are split per component (schema, web/admin, kamusers, agis, ..)
- [X] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 

#### Description

#### Additional information

2022-08-02 15:45 UTC, ironArt3mis commented
Rebase completed.

2022-08-03 07:56 UTC, mmadariaga requested changes

2022-08-03 07:56 UTC, mmadariaga commented on microservices/realtime/config/packages/security.yaml
> +#            anonymous: true
Remove this line or set it to false

2022-08-03 07:56 UTC, mmadariaga commented on web/rest/client/config/packages/framework.yaml
> +    router: {utf8: true }
use same sintax as above

2022-08-03 08:37 UTC, ironArt3mis commented
Rebase completed.

2022-08-03 09:40 UTC, merged