Provider 435 new symfony microservice project for provision
irontec/ivozprovider pull request #1880
Opened 2022-08-05 11:44 UTC by ironBatista

#### Type Of Change 
- [ ] Small bug fix
- [X] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [X] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [X] Commits are split per component (schema, web/admin, kamusers, agis, ..)
- [X] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 

#### Description

#### Additional information

2022-08-05 11:45 UTC, ironArt3mis commented
Rebase completed.

2022-08-05 11:49 UTC, mmadariaga requested changes

2022-08-05 11:49 UTC, mmadariaga commented on microservices/provision/bin/run
> +./run-call-csv-to-email
Remove this file

2022-08-05 11:49 UTC, mmadariaga commented on microservices/provision/bin/run-billable-calls
> +use Symfony\Component\Console\Input\ArgvInput;
Remove this file

2022-08-05 11:49 UTC, mmadariaga commented on microservices/provision/bin/run-billable-calls-historic
> +use Symfony\Component\Console\Input\ArgvInput;
Remove this file

2022-08-05 11:49 UTC, mmadariaga commented on microservices/provision/bin/run-call-csv-to-email
> +use Symfony\Component\Console\Input\ArgvInput;
Remove this file

2022-08-05 11:49 UTC, mmadariaga commented on microservices/provision/bin/run-invoice-scheduler
> +use Symfony\Component\Console\Input\ArgvInput;
Remove this file

2022-08-05 11:49 UTC, mmadariaga commented on microservices/provision/bin/run-voicemail-messages
> +use Symfony\Component\Console\Input\ArgvInput;
Remove this file

2022-08-05 11:49 UTC, mmadariaga commented on microservices/provision/psalm-baseline.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Are these real issues or just a copy? Remove it if copied

2022-08-09 08:26 UTC, ironArt3mis commented
Rebase completed.

2022-08-31 08:50 UTC, mmadariaga approved these changes

2022-09-08 08:33 UTC, merged