Provider 79 serve generic provision templates
irontec/ivozprovider pull request #1902
Opened 2022-09-15 14:30 UTC by ironBatista

#### Type Of Change 
- [ ] Small bug fix
- [X] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [X] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [X] Commits are split per component (schema, web/admin, kamusers, agis, ..)
- [X] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 

#### Description
The first part of the provision migration, I've called /provision/v2 in the apache config site. This feature serve a generic template.

#### Additional information

2022-09-15 14:31 UTC, ironArt3mis commented
Rebase completed.

2022-09-15 14:36 UTC, ironArt3mis commented
Rebase completed.

2022-09-19 09:32 UTC, mmadariaga requested changes

2022-09-19 09:32 UTC, mmadariaga commented on library/Ivoz/Provider/Domain/Model/TerminalModel/TerminalModelRepository.php
> +     * @return TerminalModelInterface | null
Put this hint in php code findOneByGenericTemplate(string $genericUrlPattern): ?TerminalModelInterface

2022-09-19 09:32 UTC, mmadariaga commented on library/Ivoz/Provider/Domain/Model/User/UserRepository.php
> +     * @return UserInterface
Put this hint in php code

2022-09-19 09:32 UTC, mmadariaga commented on microservices/provision/src/Controller/ProvisionController.php
> +    {
) {

2022-09-19 09:32 UTC, mmadariaga commented on microservices/provision/src/Services/Provision.php
> +    )
) {

2022-09-19 09:32 UTC, mmadariaga commented on microservices/provision/src/Services/Provision.php
> +//        if(!$terminal){
Remove comments

2022-09-19 09:32 UTC, mmadariaga commented on microservices/provision/src/Services/Provision.php
> +        $terminal = $this->_getTerminalByUrl($specificUrlPattern);
Unused

2022-09-19 09:32 UTC, mmadariaga commented on microservices/provision/src/Services/Provision.php
> +    private function _getTerminalByUrl($terminalUrl)
unused

2022-09-19 09:32 UTC, mmadariaga commented on microservices/provision/templates/basic.txt
> +<!DOCTYPE HTML>
This is an invoice template, not a provision one

2022-09-19 09:32 UTC, mmadariaga commented on microservices/provision/templates/detailed.txt
> +<!DOCTYPE HTML>
not provision template

2022-09-19 09:32 UTC, mmadariaga commented on microservices/provision/templates/footer.txt
> +<!DOCTYPE HTML>
Not provision template

2022-09-19 09:32 UTC, mmadariaga commented on microservices/provision/templates/header.txt
> +<!DOCTYPE HTML>
Not provision temnplate

2022-09-19 12:30 UTC, ironArt3mis commented
Rebase completed.

2022-09-20 09:34 UTC, mmadariaga approved these changes

2022-09-20 09:34 UTC, mmadariaga commented on microservices/provision/src/Services/Provision.php
> +class Provision extends AbstractController
Don't extend AbstractController, just register controllers as a service

2022-09-21 10:53 UTC, ironArt3mis commented
Rebase completed.

2022-09-21 15:05 UTC, merged