Provider 54 new brand portals
irontec/ivozprovider pull request #1906
Opened 2022-09-26 14:12 UTC by mmadariaga

#### Type Of Change 
- [ ] Small bug fix
- [ ] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [ ] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [ ] Commits are split per component (schema, web/admin, kamusers, agis, ..)
- [ ] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 

#### Description

#### Additional information

2022-10-13 09:32 UTC, Kaian requested changes

2022-10-13 09:32 UTC, Kaian commented on web/portal/brand/src/entities/ActiveCalls/ActiveCalls.tsx
> +import { BillableCallProperties } from './ActiveCallsProperties';
BillableCallProperties -> ActiveCallsProperties

2022-10-28 09:42 UTC, ironArt3mis commented
Rebase completed.

2022-11-08 08:16 UTC, Kaian commented on web/portal/brand/src/entities/Company/Form.tsx
> +  console.log('isRetail', isRetail);
debugging lines here

2022-11-08 08:16 UTC, Kaian commented on web/portal/brand/src/entities/Company/Company.tsx
> +    label: _('Balance'), //WTF
WTF do you mean with WTF!

2022-11-08 08:16 UTC, Kaian commented on web/portal/brand/src/entities/Company/Form.tsx
> +  //const isWholesale = type === 'wholesale';
Commented code

2022-11-08 08:17 UTC, Kaian commented
I have added 2 commits here:
 - DDI description field from #1926 
 - Apache configuration to access this portal through /brand

Keep up the good work! :muscle:

2022-11-09 09:36 UTC, Kaian approved these changes

2022-11-09 10:00 UTC, merged