Provider 478 serve specific provision templates
irontec/ivozprovider pull request #1916
Opened 2022-10-25 13:46 UTC by ironBatista

#### Type Of Change 
- [ ] Small bug fix
- [ X ] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [ X ] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [ X ] Commits are split per component (schema, web/admin, kamusers, agis, ..)
- [ X ] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 

#### Description
This issue modifies the existent provision microservice to perform a provisioning process for specific provision templates of different terminal manufacturers and their corresponding models.

#### Additional information

2022-10-25 13:47 UTC, ironArt3mis commented
Rebase completed.

2022-10-28 09:47 UTC, mmadariaga requested changes

2022-10-28 09:47 UTC, mmadariaga commented on library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/TerminalModelDoctrineRepository.php
> +
remove empty line

2022-10-28 09:47 UTC, mmadariaga commented on library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/TerminalModelDoctrineRepository.php
> +    public function findOneById(int $terminalModelId): ?TerminalModelInterface
public function find

2022-10-28 09:47 UTC, mmadariaga commented on library/Ivoz/Provider/Domain/Model/Brand/BrandRepository.php
> +    public function findById(int $id): ?BrandInterface;
don't wrap find method

2022-10-28 09:47 UTC, mmadariaga commented on microservices/provision/src/Controller/ProvisionController.php
>              $routeParams = $request->attributes->get('_route_params');
`/** @var array{configFile: string, mac: string} $routeParams */`

2022-10-28 09:47 UTC, mmadariaga commented on microservices/provision/src/Controller/ProvisionController.php
>              /** @var string $configFile */
remove this line

2022-10-28 09:47 UTC, mmadariaga commented on microservices/provision/config/routes.yaml
> +    path: /{configFile}/{mac}
use a diferent controller for specific provisioning

2022-10-28 09:48 UTC, mmadariaga commented on profiles/portal/etc/apache2/sites-available/030-ivozprovider-prov.conf
> +#    SSLProtocol TLSv1
why?

2022-11-07 08:01 UTC, mmadariaga requested changes

2022-11-07 12:16 UTC, ironArt3mis commented
Rebase completed.

2022-11-08 08:20 UTC, ironArt3mis commented
Rebase completed.

2022-11-08 15:40 UTC, mmadariaga approved these changes

2022-11-08 15:40 UTC, mmadariaga commented on library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/TerminalDoctrineRepository.php
> +    public function findByMacs(array $macs): ?array
Add ORM test for this method

2022-11-08 15:40 UTC, mmadariaga commented on library/psalm-baseline.xml
> -    <PossiblyUnusedReturnValue occurrences="4">
I don't understand why this is gone

2022-11-08 15:40 UTC, mmadariaga commented on library/Ivoz/Provider/Domain/Model/User/UserRepository.php
> -    public function findOneByTerminalId(
I don't see any reference to this method in the PR. If it's actually required to be removed, you should erase it from doctrine repository as well

2022-11-08 15:40 UTC, mmadariaga commented on microservices/provision/psalm.xml
> +        <UnusedProperty errorLevel="suppress"/>
are these required?

2022-11-08 15:40 UTC, mmadariaga commented on microservices/provision/src/Services/Provision.php
> +        private TerminalRepository $terminalRepository,
This service is far too complex, split into two services (generic / specific)

2022-11-08 15:40 UTC, mmadariaga commented on microservices/provision/src/Services/Provision.php
> +        $isHttps = isset($_SERVER['HTTPS']) && !empty($_SERVER['HTTPS']);
this shoud go into the controller because it's part of infrastructure (every $_SERVER, $_POST, etc. access)

2022-11-22 10:23 UTC, mmadariaga requested changes

2022-11-22 10:23 UTC, mmadariaga commented on library/Ivoz/Provider/Domain/Model/User/UserRepository.php
> +    );
```suggestion
    ): ?UserInterface;
```

2022-11-22 10:23 UTC, mmadariaga commented on library/Ivoz/Provider/Domain/Model/User/UserRepository.php
> +    /**
Remove this comment

2022-11-22 10:23 UTC, mmadariaga commented on microservices/provision/psalm.xml
> +        <InvalidScalarArgument errorLevel="suppress" />
This should not be necessary

2022-11-22 10:23 UTC, mmadariaga commented on microservices/provision/src/Services/ProvisionSpecific.php
> +            /** @phpstan-ignore-next-line */
We probably can solve this

2022-11-22 10:23 UTC, mmadariaga commented on microservices/provision/src/Services/ProvisionSpecific.php
> +        return pathinfo($route, PATHINFO_EXTENSION);
pathinfo with options is always a string, never array

2022-11-22 10:23 UTC, mmadariaga commented on microservices/provision/src/Services/TemplateRenderer.php
> +    /** @phpstan-ignore-next-line  */
We probably can remove this line

2022-11-22 10:23 UTC, mmadariaga commented on microservices/provision/src/Services/TemplateRenderer.php
> +         * @var  string $key
```suggestion
         * @var string $key
```

2022-11-22 10:23 UTC, mmadariaga commented on microservices/provision/src/Services/TemplateRenderer.php
> +         * @var DataTransferObjectInterface $value
Use this hint in the constructor

2022-11-22 17:02 UTC, mmadariaga requested changes

2022-11-23 11:13 UTC, ironArt3mis commented
Rebase completed.

2022-11-23 12:06 UTC, mmadariaga commented on microservices/provision/src/Services/ProvisionSpecific.php
> +                /** @var int $end */
```suggestion
                /** @var int<min, 0> $end */
```

2022-11-24 12:05 UTC, mmadariaga approved these changes

2022-11-24 12:06 UTC, ironArt3mis commented
Rebase completed.

2022-11-24 12:12 UTC, merged