Provider 503 expose carrier server status in brand api
irontec/ivozprovider pull request #1921
Opened 2022-10-31 10:07 UTC by ironBatista

#### Type Of Change 
- [ ] Small bug fix
- [X] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [X] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [X] Commits are split per component (schema, web/admin, kamusers, agis, ..)
- [X] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 

#### Description
Created custom endpoint for carrier_server, for status retrieval.

#### Additional information

2022-10-31 10:07 UTC, ironArt3mis commented
Rebase completed.

2022-11-03 15:27 UTC, mmadariaga requested changes

2022-11-03 15:27 UTC, mmadariaga commented on library/Ivoz/Kam/Infrastructure/Kamailio/TrunksClient.php
> +
revert this change

2022-11-03 15:27 UTC, mmadariaga commented on library/Ivoz/Provider/Application/Service/CarrierServer/CarrierServerDtoAssembler.php
> +            $dumpGw = $this->trunksClient->getLcrGatewayInfo(
$lcrGatewayInfo would be a better name

2022-11-03 15:27 UTC, mmadariaga commented on library/Ivoz/Provider/Domain/Model/CarrierServer/CarrierServerDto.php
> +                    'expires'
this attributes do not exist in CarrierServerRegistrationStatus

2022-11-03 15:27 UTC, mmadariaga commented on library/Ivoz/Provider/Domain/Model/CarrierServer/CarrierServerRegistrationStatus.php
> +        }
``
```suggestion
            $this->setRegistered(
                $statusCode === 0
            );
```

2022-11-03 15:27 UTC, mmadariaga commented on web/rest/brand/config/api/raw/provider.yml
> +        ]
Missing API tests

2022-11-04 12:49 UTC, mmadariaga approved these changes

2022-11-04 12:50 UTC, ironArt3mis commented
Rebase completed.

2022-11-04 13:24 UTC, ironArt3mis commented
Rebase completed.

2022-11-04 13:25 UTC, merged