core: Added status to DdiProviderRegistration entity
irontec/ivozprovider pull request #1928
Opened 2022-11-07 16:28 UTC by ironBatista

#### Type Of Change 
- [ ] Small bug fix
- [X] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [X] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [ ] Commits are split per component (schema, web/admin, kamusers, agis, ..)
- [X] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 

#### Description
Added registration status of DdiProviderRegistration entity with a custom endpoint.

#### Additional information

2022-11-07 16:29 UTC, ironArt3mis commented
Rebase completed.

2022-11-08 08:20 UTC, ironArt3mis commented
Rebase completed.

2022-11-08 08:21 UTC, ironArt3mis commented
Rebase completed.

2022-11-08 08:22 UTC, ironArt3mis commented
Rebase completed.

2022-11-08 15:50 UTC, mmadariaga commented on library/Ivoz/Provider/Domain/Model/DdiProviderRegistration/DdiProviderRegistrationDto.php
> +        if ($context === self::CONTEXT_STATUS) {
add API tests

2022-11-10 10:44 UTC, mmadariaga requested changes

2022-11-14 14:15 UTC, mmadariaga approved these changes

2022-11-15 10:22 UTC, ironArt3mis commented
Rebase completed.

2022-11-15 12:04 UTC, ironArt3mis commented
Rebase completed.

2022-11-15 16:12 UTC, merged