Provider 553 nuevos campos en cs vs programados para adamo
irontec/ivozprovider pull request #1930
Opened 2022-11-10 09:20 UTC by ironBatista

#### Type Of Change 
- [ ] Small bug fix
- [X] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [X] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [X] Commits are split per component (schema, web/admin, kamusers, agis, ..)
- [X] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 

#### Description
Added there new ordered fields in Csv of CallCsvScheduler.

#### Additional information

2022-11-10 09:21 UTC, ironArt3mis commented
Rebase completed.

2022-11-10 10:39 UTC, mmadariaga commented on web/rest/brand/features/provider/billableCalls/getBillableCalls.feature
> +              "carrierName": null,
Add some data into fixtures

2022-11-10 10:40 UTC, mmadariaga commented on web/rest/client/features/provider/billableCall/getBillableCall.feature
> +callid,startTime,duration,caller,callee,price,destinationName,ratingPlanName,endpointType,endpointId,endpointName,direction,id,ddi
this is wrong

2022-11-16 17:27 UTC, mmadariaga requested changes

2022-11-16 17:27 UTC, mmadariaga commented on web/rest/client/features/provider/queue/getQueue.feature
> +          "preventMissedCalls": 1,
Changes in queue tests have nothing to do with this PR. Revert them

2022-11-17 09:59 UTC, mmadariaga approved these changes

2022-11-17 11:12 UTC, merged