portal/brand: Added brand portal routing forms
irontec/ivozprovider pull request #1936
Opened 2022-11-15 10:42 UTC by fmendozzac

#### Type Of Change 
- [ ] Small bug fix
- [x] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [x] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [x] Commits are split per component (schema, web/admin, kamusers, agis, ..)
- [x] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 
- [ ] Upport from existing Pull request #XXXX

#### Description

#### Additional information

2022-11-15 10:42 UTC, ironArt3mis commented
Rebase completed.

2022-11-22 11:22 UTC, mmadariaga requested changes

2022-11-25 12:06 UTC, mmadariaga requested changes

2022-11-25 12:06 UTC, mmadariaga commented on web/portal/brand/src/entities/OutgoingRouting/Form.tsx
> +        // 'carrier',
@TODO or remove

2022-11-25 12:09 UTC, mmadariaga commented on web/portal/brand/src/entities/OutgoingRouting/Form.tsx
> +      fields: ['type', 'routingPattern'],
type.group must show a cuntry selector

2022-11-25 12:14 UTC, mmadariaga commented on web/portal/brand/src/entities/OutgoingRouting/Form.tsx
>          'routingMode',
Cannot be changed on edit

2022-11-25 12:52 UTC, mmadariaga commented on web/portal/brand/src/entities/OutgoingRouting/Form.tsx
> +        // 'carrier',
Carries is not being selected on edit

2022-11-29 15:12 UTC, mmadariaga approved these changes

2022-11-29 15:21 UTC, merged