portal/brand: Added billing portal forms
irontec/ivozprovider pull request #1939
Opened 2022-11-17 15:41 UTC by fmendozzac

#### Type Of Change 
- [ ] Small bug fix
- [x] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [x] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [x] Commits are split per component (schema, web/admin, kamusers, agis, ..)
- [x] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 
- [ ] Upport from existing Pull request #XXXX

#### Description

#### Additional information

2022-11-17 15:41 UTC, ironArt3mis commented
Rebase completed.

2022-11-22 11:01 UTC, mmadariaga requested changes

2022-11-22 11:01 UTC, mmadariaga commented on web/portal/brand/src/entities/BalanceNotification/Form.tsx
> +        'notificationTemplate',
This is not sorted alphabetically

2022-11-23 16:31 UTC, mmadariaga approved these changes

2022-11-23 21:30 UTC, closed without merging