portal/brand: Added invoicing forms
irontec/ivozprovider pull request #1941
Opened 2022-11-22 14:19 UTC by fmendozzac

#### Type Of Change 
- [ ] Small bug fix
- [x] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [x] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [x] Commits are split per component (schema, web/admin, kamusers, agis, ..)
- [x] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 
- [ ] Upport from existing Pull request #XXXX

#### Description

#### Additional information

2022-11-22 14:20 UTC, ironArt3mis commented
Rebase completed.

2022-11-22 15:25 UTC, mmadariaga requested changes

2022-11-22 15:25 UTC, mmadariaga commented on web/portal/brand/src/entities/Invoice/Form.tsx
> +      fields: ['total', 'taxRate', 'totalWithTax'],
taxRate must be editable

2022-11-22 15:25 UTC, mmadariaga commented on web/portal/brand/src/entities/Invoice/Form.tsx
> +      fields: ['status', 'pdf'],
pdf must be read only

2022-11-24 11:58 UTC, mmadariaga requested changes

2022-11-24 11:58 UTC, mmadariaga commented on web/portal/brand/src/entities/FixedCost/FixedCost.tsx
> +    type: 'integer',
This should not be necessary in ivoz-ui 0.10.3

2022-11-24 12:02 UTC, mmadariaga approved these changes

2022-11-24 12:17 UTC, merged