portal/brand: Added settings forms
irontec/ivozprovider pull request #1942
Opened 2022-11-22 15:14 UTC by fmendozzac

#### Type Of Change 
- [ ] Small bug fix
- [x] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [x] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [x] Commits are split per component (schema, web/admin, kamusers, agis, ..)
- [x] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 
- [ ] Upport from existing Pull request #XXXX

#### Description

#### Additional information

2022-11-22 15:15 UTC, ironArt3mis commented
Rebase completed.

2022-11-22 15:39 UTC, mmadariaga requested changes

2022-11-22 15:39 UTC, mmadariaga commented on web/portal/brand/src/entities/WebPortal/Form.tsx
> +      fields: ['klearTheme', 'logo'],
klearTheme must be an enum

2022-11-22 15:39 UTC, mmadariaga commented on web/portal/brand/src/entities/NotificationTemplateContent/Form.tsx
> +      fields: ['bodyType', 'subject', 'body'],
body must be of type textarea

2022-11-22 15:39 UTC, mmadariaga commented on web/portal/brand/src/entities/MusicOnHold/Form.tsx
> +      fields: ['originalFile', 'encodedFile'],
encodedFile must be readOnly

2022-11-22 15:39 UTC, mmadariaga commented on web/portal/brand/src/entities/BrandService/Form.tsx
> +      fields: ['service'],
Service must show only unassigned services and must be readOnly on edit

2022-11-24 16:59 UTC, ironArt3mis commented
Rebase completed.

2022-11-29 10:30 UTC, mmadariaga requested changes

2022-11-29 10:30 UTC, mmadariaga commented on web/portal/brand/src/entities/WebPortal/WebPortal.tsx
> +    enum: {},
Missing values

```
    irontec-red: Irontec-red
    irontec-blue: Irontec-blue
    absolution: Absolution
    absolution-green: Absolution-green
    absolution-red: Absolution-red
    aristo: Aristo
    aristo-dark: Aristo-dark
    aristo-green: Aristo-green
    aristo-red: Aristo-red
    delta: Delta
    redmond-red: Redmond-red
    twitter: Twitter
    tedra: Tedra
    pinkpat: Pinkpat
    redinn: Redinn
    grayidec: Grayidec
    base: Base
    black-tie: Black-tie
    blitzer: Blitzer
    cupertino: Cupertino
    dark-hive: Dark-hive
    dot-luv: Dot-luv
    eggplant: Eggplant
    excite-bike: Excite-bike
    flick: Flick
    hot-sneaks: Hot-sneaks
    humanity: Humanity
    le-frog: Le-frog
    mint-choc: Mint-choc
    overcast: Overcast
    pepper-grinder: Pepper-grinder
    redmond: Redmond
    smoothness: Smoothness
    south-street: South-street
    start: Start
    sunny: Sunny
    swanky-purse: Swanky-purse
    trontastic: Trontastic
    ui-darkness: Ui-darkness
    ui-lightness: Ui-lightness
    vader: Vader
```

2022-11-29 10:30 UTC, mmadariaga commented on web/portal/brand/src/entities/NotificationTemplate/Form.tsx
> +      fields: ['name', 'type'],
Wrong values in type. Valid values are:

```
          'voicemail': 'Voicemail'
          'fax': 'Fax'
          'lowbalance': 'Low balance'
          'invoice': 'Invoice'
          'callCsv': 'Call CSV'
          'maxDailyUsage': 'Max daily usage'
```

2022-11-29 10:30 UTC, mmadariaga commented on web/portal/brand/src/entities/MusicOnHold/MusicOnHold.tsx
> +    readOnly: true,
We've an error here: "Empty download path"

2022-11-30 17:20 UTC, mmadariaga approved these changes

2022-11-30 17:20 UTC, merged