Provider 525 review platform api collection responses
irontec/ivozprovider pull request #1946
Opened 2022-11-24 15:31 UTC by ironBatista

#### Type Of Change 
- [ ] Small bug fix
- [X] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [X] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [X] Commits are split per component (schema, web/admin, kamusers, agis, ..)
- [X] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 
- [ ] Upport from existing Pull request #XXXX

#### Description
This issue ensures that API response collections match columns from Klear lists under the Platform section.

#### Additional information

2022-11-24 15:31 UTC, ironArt3mis commented
Rebase completed.

2022-11-29 09:12 UTC, mmadariaga requested changes

2022-11-29 09:12 UTC, mmadariaga commented on library/Ivoz/Provider/Domain/Model/Domain/DomainDto.php
> +                // @TODO client
Shouldn't this be part of this PR as well?

2022-12-01 15:11 UTC, ironArt3mis commented
Rebase completed.

2022-12-01 15:41 UTC, mmadariaga requested changes

2022-12-01 15:41 UTC, mmadariaga commented on library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/BrandDoctrineRepository.php
> +            ->where('self.domainUsers in (:domainUsers)');
in?

2022-12-01 15:41 UTC, mmadariaga commented on library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/CompanyDoctrineRepository.php
> +            ->where('self.domainUsers in (:domainUsers)');
in?

2022-12-01 15:41 UTC, mmadariaga commented on web/rest/platform/features/provider/notificationTemplate/postNotificationTemplate.feature
> +    And the JSON should be like:
No reason to use "like" here. Use `the JSON should be equal to` instead

2022-12-14 09:45 UTC, mmadariaga requested changes

2022-12-14 09:45 UTC, mmadariaga commented on schema/tests/Provider/Company/CompanyRepositoryTest.php
> +    public function it_finds_one_by_domain_users(){
Either call this method `public function it_finds_one_by_domain() {` or call repository method `findOneByDomainUsers`

2022-12-14 15:26 UTC, mmadariaga approved these changes

2022-12-14 15:52 UTC, ironArt3mis commented
Rebase completed.

2022-12-14 16:00 UTC, merged