Review brand api default collections order
irontec/ivozprovider pull request #1972
Opened 2023-01-02 19:54 UTC by ironBatista

#### Type Of Change 
- [ ] Small bug fix
- [X] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [X] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [X] Commits are split per component (schema, web/admin, kamusers, agis, ..)
- [X] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 
- [ ] Upport from existing Pull request #XXXX

#### Description
Reviewed Brand section from clear and adapted new portals to ensure that it serves at least the same data.

#### Additional information

2023-01-10 10:57 UTC, mmadariaga requested changes

2023-01-10 10:57 UTC, mmadariaga commented on web/rest/brand/config/api/raw/provider.yml
> +Ivoz\Provider\Domain\Model\MediaRelaySet\MediaRelaySet:
MediaRelaySet is a platform entity

2023-01-11 14:52 UTC, mmadariaga commented on web/portal/brand/src/entities/BillableCall/BillableCall.tsx
> +    'direction',
update API tests

2023-01-13 11:40 UTC, mmadariaga approved these changes

2023-01-13 11:44 UTC, ironArt3mis commented
Rebase completed.

2023-01-16 09:59 UTC, mmadariaga requested changes
Squash commits

2023-01-16 17:05 UTC, merged