Impossible to use destination rate groups file importer arguments from api
irontec/ivozprovider pull request #1973
Opened 2023-01-04 12:29 UTC by ironBatista

#### Type Of Change 
- [ ] Small bug fix
- [X] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [X] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [X] Commits are split per component (schema, web/admin, kamusers, agis, ..)
- [X] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 
- [ ] Upport from existing Pull request #XXXX

#### Description
This issue inserts new data for destinationRateGroups petitions.

#### Additional information

2023-01-10 10:25 UTC, mmadariaga requested changes
Update API tests as well

2023-01-10 10:25 UTC, mmadariaga commented on library/Ivoz/Provider/Domain/Model/DestinationRateGroup/FileImporterArguments.php
> +            $this->ignoreFirst = $ignoreFirst;
fix indentation here

2023-01-16 10:01 UTC, ironArt3mis commented
Rebase completed.

2023-01-16 10:10 UTC, mmadariaga requested changes

2023-01-16 10:10 UTC, mmadariaga commented on web/rest/brand/features/provider/destinationRateGroup/postDestinationRateGroup.feature
> +              "importerArguments": {
Missing importer arguments in POST

2023-01-16 10:10 UTC, mmadariaga commented on web/rest/brand/features/provider/destinationRateGroup/putDestinationRateGroup.feature
> +    "currency": "1"
Missing importer arguments

2023-01-16 10:10 UTC, mmadariaga commented on web/rest/brand/features/provider/destinationRateGroup/putDestinationRateGroup.feature
> +  Scenario: Update a destination rate group
This test replaces the former one

2023-01-25 13:27 UTC, ironBatista commented on library/Ivoz/Provider/Domain/Model/DestinationRateGroup/DestinationRateGroupDto.php
> +        $includeImporterArgumens = !in_array($context, self::CONTEXTS_WITHOUT_IMPORTER_ARGUMENTS);
Possible typo? $includeImporterArgumens -> $includeImporterArguments

2023-01-25 13:49 UTC, mmadariaga approved these changes

2023-01-25 14:02 UTC, merged