Initial Address book support
irontec/ivozprovider pull request #1995
Opened 2023-01-25 14:12 UTC by Kaian

#### Type Of Change 
- [ ] Small bug fix
- [X] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [X] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [X] Commits are split per component (schema, web/admin, kamusers, agis, ..)
- [X] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 
- [X] Upport from existing Pull request #1984

#### Description
Add new business table to store Contacts information.
Contacts for existing vPBX users will be added and maintained automatically.

Current contacts fields:
 - Name
 - Lastname
 - Email
 - Work Phone
 - Mobile Phone
 - Other Phone

Currently Contacts are not being used in any logic but can be created and retrieved through Rest API.

#### Additional information

2023-01-27 08:03 UTC, mmadariaga requested changes

2023-01-27 08:03 UTC, mmadariaga commented on web/portal/client/src/entities/Contact/Contact.tsx
> +    console.log(allowDelete);
Remove console logs

2023-01-27 08:36 UTC, Kaian commented on web/portal/client/src/entities/Contact/Contact.tsx
> +    console.log(allowDelete);
Good catch! :+1:

2023-01-27 08:41 UTC, Kaian commented on schema/DoctrineMigrations/Version20230113114920.php
> +final class Version20230113114920 extends AbstractMigration
Fixed!

2023-01-27 09:14 UTC, Kaian commented
Updated with requested changes.
Also added:

- Changed API spec to add delete restrictions on user contacts (those with userId != NULL)
- Updated DTO denormalize to ignore some field updates in user contacts 


Please, review those extra changes too :pray: 

Thanks!

2023-01-27 12:39 UTC, mmadariaga approved these changes

2023-01-30 11:47 UTC, Kaian commented
Added this fixture of a contact from the second company:

https://github.com/irontec/ivozprovider/blob/77a913b9be870b2329044573fec261c7a10981f2/library/DataFixtures/ORM/ProviderContact.php#L74-L88

And this test:

https://github.com/irontec/ivozprovider/blob/bb9e15434890714553634c70ba5e1f217b6a32d1/web/rest/client/features/provider/contact/removeContact.feature#L14-L19

2023-01-30 14:22 UTC, mmadariaga commented
LGTM

2023-01-30 16:42 UTC, merged