web/portal: Added Teminal Manufacturer to platform portal
irontec/ivozprovider pull request #2016
Opened 2023-02-01 16:25 UTC by fmendozzac

#### Type Of Change 
- [ ] Small bug fix
- [x] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [x] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [x] Commits are split per component (schema, web/admin, kamusers, agis, ..)
- [x] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 
- [ ] Upport from existing Pull request #XXXX

#### Description
Added Teminal Manufacturer entity to platform portal

#### Additional information

2023-02-01 16:26 UTC, ironArt3mis commented
Rebase completed.

2023-02-02 09:46 UTC, mmadariaga requested changes

2023-02-02 09:46 UTC, mmadariaga commented on web/portal/platform/src/entities/TerminalManufacturer/ForeignKeyGetter.tsx
> +/** TODO remove this file unless you need to change default behaviour **/
remove this file

2023-02-02 09:46 UTC, mmadariaga commented on web/portal/platform/src/entities/TerminalManufacturer/ForeignKeyResolver.tsx
> +/** TODO remove this file unless you need to change default behaviour **/
remove this file

2023-02-02 09:46 UTC, mmadariaga commented on web/portal/platform/src/entities/TerminalManufacturer/SelectOptions.ts
> +      const options: any = {};
use array options so that it can be sorted

```suggestion
      const options: DropdownChoices = [];
```

2023-02-02 09:46 UTC, mmadariaga commented on web/portal/platform/src/entities/TerminalManufacturer/SelectOptions.ts
> +    (data: any) => {
```suggestion
    (data: EntityValues) => {
```

2023-02-02 09:46 UTC, mmadariaga commented on web/portal/platform/src/entities/TerminalManufacturer/TerminalManufacturer.tsx
> +    required: false,
Is this diferent from API spec? You should not set this if so

2023-02-02 09:46 UTC, mmadariaga commented on web/portal/platform/src/entities/TerminalManufacturer/TerminalManufacturer.tsx
> +  title: _('Terminal Manufacturers', { count: 2 }),
```suggestion
  title: _('Terminal Manufacturer', { count: 2 }),
```

2023-02-02 09:46 UTC, mmadariaga commented on web/portal/platform/src/entities/TerminalManufacturer/TerminalManufacturer.tsx
> +  toStr: (row: any) => row.iden,
any is forbidden

2023-02-02 09:46 UTC, mmadariaga commented on web/portal/platform/src/entities/TerminalModel/ForeignKeyGetter.tsx
> +/** TODO remove this file unless you need to change default behaviour **/
Remove this file

2023-02-02 09:46 UTC, mmadariaga commented on web/portal/platform/src/entities/TerminalModel/ForeignKeyResolver.tsx
> +/** TODO remove this file unless you need to change default behaviour **/
Remove this file

2023-02-02 09:46 UTC, mmadariaga commented on web/portal/platform/src/entities/TerminalModel/SelectOptions.ts
> +    (data: any) => {
any is forbidden

2023-02-02 09:46 UTC, mmadariaga commented on web/portal/platform/src/entities/TerminalModel/TerminalModel.tsx
> +    required: false,
probably unnecessary

2023-02-02 09:46 UTC, mmadariaga commented on web/portal/platform/src/entities/TerminalModel/TerminalModel.tsx
> +    required: false,
Review all required properties

2023-02-02 09:46 UTC, mmadariaga commented on web/portal/platform/src/entities/TerminalModel/TerminalModel.tsx
> +  toStr: (row: any) => row.iden,
any is forbiden

2023-02-02 09:46 UTC, mmadariaga commented on web/portal/platform/src/entities/TerminalModel/TerminalModel.tsx
> +  title: _('Terminal Models', { count: 2 }),
```suggestion
  title: _('Terminal Model', { count: 2 }),
```

2023-02-02 12:49 UTC, ironArt3mis commented
Rebase completed.

2023-02-02 14:41 UTC, mmadariaga requested changes

2023-02-02 14:41 UTC, mmadariaga commented on web/portal/platform/src/entities/TerminalManufacturer/SelectOptions.ts
> +    (data) => {
```suggestion
    (data: EntityValues) => {
```

2023-02-02 14:41 UTC, mmadariaga commented on web/portal/platform/src/entities/TerminalModel/SelectOptions.ts
> +    (data) => {
```suggestion
    (data: EntityValues) => {
```

2023-02-02 14:41 UTC, mmadariaga commented on web/portal/platform/src/entities/TerminalModel/SelectOptions.ts
> +      const options: any = {};
Any is forbidden and use array values

2023-02-02 14:41 UTC, mmadariaga commented on web/portal/platform/src/entities/TerminalModel/TerminalModel.tsx
> +    required: true,
Already in the API

2023-02-02 14:41 UTC, mmadariaga commented on web/portal/platform/src/entities/TerminalModel/TerminalModel.tsx
> +  toStr: (row: EntityValues) => row.iden as string,
```suggestion
  toStr: (row: TerminalModelPropertyList<EntityValue>) => row.iden as string,
```

2023-02-03 09:27 UTC, mmadariaga approved these changes

2023-02-03 11:11 UTC, merged