Brands & suboptions in Platform portal
irontec/ivozprovider pull request #2017
Opened 2023-02-01 16:31 UTC by ironBatista

#### Type Of Change 
- [ ] Small bug fix
- [X] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [X] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [X] Commits are split per component (schema, web/admin, kamusers, agis, ..)
- [X] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 
- [ ] Upport from existing Pull request #XXXX

#### Description

#### Additional information

2023-02-02 09:26 UTC, fmendozzac commented on web/portal/platform/src/entities/Currency/Currency.tsx
> +  toStr: (row: any) => row.id,
Maybe 'id' is not the best toStr

2023-02-02 10:30 UTC, fmendozzac commented on web/portal/platform/src/entities/Currency/Currency.tsx
> +  toStr: (row: any) => row.id,
any is forbidden

2023-02-02 10:32 UTC, fmendozzac commented on web/portal/platform/src/entities/Brand/ForeignKeyGetter.tsx
> +/** TODO remove this file unless you need to change default behaviour **/
Remove this file

2023-02-02 10:32 UTC, fmendozzac commented on web/portal/platform/src/entities/Brand/ForeignKeyResolver.tsx
> +/** TODO remove this file unless you need to change default behaviour **/
Remove this file

2023-02-02 10:33 UTC, fmendozzac commented on web/portal/platform/src/entities/Brand/SelectOptions.ts
> +    (data: any) => {
any is forbidden

2023-02-02 10:33 UTC, fmendozzac commented on web/portal/platform/src/entities/Currency/ForeignKeyGetter.tsx
> +/** TODO remove this file unless you need to change default behaviour **/
Remove this file

2023-02-02 10:34 UTC, fmendozzac commented on web/portal/platform/src/entities/Currency/ForeignKeyResolver.tsx
> +/** TODO remove this file unless you need to change default behaviour **/
Remove this file

2023-02-02 10:35 UTC, fmendozzac commented on web/portal/platform/src/entities/Currency/Form.tsx
> +      legend: _('Main'),
it could go empty

2023-02-02 10:36 UTC, fmendozzac commented on web/portal/platform/src/entities/Feature/Form.tsx
> +      legend: _('Main'),
it could be empty

2023-02-02 10:37 UTC, fmendozzac commented on web/portal/platform/src/entities/Feature/SelectOptions.ts
> +    (data: any) => {
any is forbidden

2023-02-02 10:38 UTC, fmendozzac commented on web/portal/platform/src/entities/Language/Form.tsx
> +      legend: _('Main'),
it could be empty

2023-02-02 10:41 UTC, fmendozzac commented on web/portal/platform/src/entities/Feature/Feature.tsx
> +  toStr: (row: any) => row.name.en,
any is forbidden

2023-02-02 11:07 UTC, fmendozzac commented on web/portal/platform/src/entities/Language/SelectOptions.ts
> +    (data: any) => {
any is forbidden

2023-02-06 09:24 UTC, fmendozzac commented on web/portal/platform/src/entities/Currency/SelectOptions.ts
> +    (data: any) => {
any is forbidden

2023-02-06 09:25 UTC, fmendozzac commented on web/portal/platform/src/entities/NotificationTemplate/SelectOptions/FaxSelectOptions.ts
> +    (data: any) => {
any is forbidden

2023-02-06 09:26 UTC, fmendozzac commented on web/portal/platform/src/entities/NotificationTemplate/SelectOptions/InvoiceSelectOptions.ts
> +    (data: any) => {
any is forbidden

2023-02-06 09:26 UTC, fmendozzac commented on web/portal/platform/src/entities/NotificationTemplate/SelectOptions/InvoiceSelectOptions.ts
> +      const options: any = {};
any is forbidden

2023-02-06 09:26 UTC, fmendozzac commented on web/portal/platform/src/entities/NotificationTemplate/SelectOptions/FaxSelectOptions.ts
> +      const options: any = {};
any is forbidden

2023-02-06 09:27 UTC, fmendozzac commented on web/portal/platform/src/entities/NotificationTemplate/SelectOptions/LowBalanceSelectOptions.ts
> +      const options: any = {};
any is forbidden

2023-02-06 09:27 UTC, fmendozzac commented on web/portal/platform/src/entities/NotificationTemplate/SelectOptions/MaxDailyUsageSelectOptions.ts
> +    (data: any) => {
any is forbidden

2023-02-06 09:27 UTC, fmendozzac commented on web/portal/platform/src/entities/NotificationTemplate/SelectOptions/MaxDailyUsageSelectOptions.ts
> +      const options: any = {};
any is forbidden

2023-02-06 09:27 UTC, fmendozzac commented on web/portal/platform/src/entities/NotificationTemplate/SelectOptions/SelectOptions.ts
> +    (data: any) => {
any is forbidden

2023-02-06 09:28 UTC, fmendozzac commented on web/portal/platform/src/entities/NotificationTemplate/SelectOptions/VoicemailSelectOptions.ts
> +    (data: any) => {
any is forbidden

2023-02-06 09:28 UTC, fmendozzac commented on web/portal/platform/src/entities/NotificationTemplate/SelectOptions/VoicemailSelectOptions.ts
> +      const options: any = {};
any is forbidden

2023-02-06 09:28 UTC, fmendozzac commented on web/portal/platform/src/entities/ProxyTrunk/SelectOptions.ts
> +    (data: any) => {
any is forbidden

2023-02-06 09:29 UTC, fmendozzac commented on web/portal/platform/src/entities/Brand/Field/BrandLogo.tsx
> +const BrandLogo: RouteTypeProps = (props: any): JSX.Element | null => {
any is forbidden

2023-02-06 09:29 UTC, fmendozzac commented on web/portal/platform/src/entities/Brand/Field/City.tsx
> +const City: RouteTypeProps = (props: any): JSX.Element | null => {
any is forbidden

2023-02-06 09:29 UTC, fmendozzac commented on web/portal/platform/src/entities/Brand/Field/Country.tsx
> +const Country: RouteTypeProps = (props: any): JSX.Element | null => {
any is forbidden

2023-02-06 09:29 UTC, fmendozzac commented on web/portal/platform/src/entities/Brand/Field/PostalAddress.tsx
> +const PostalAddress: RouteTypeProps = (props: any): JSX.Element | null => {
any is forbidden

2023-02-06 09:29 UTC, fmendozzac commented on web/portal/platform/src/entities/Brand/Field/PostalCode.tsx
> +const PostalCode: RouteTypeProps = (props: any): JSX.Element | null => {
any is forbidden

2023-02-06 09:30 UTC, fmendozzac commented on web/portal/platform/src/entities/Brand/Field/RegisterInfo.tsx
> +const RegisterInfo: RouteTypeProps = (props: any): JSX.Element | null => {
any is forbidden

2023-02-07 09:22 UTC, fmendozzac approved these changes

2023-02-08 09:11 UTC, mmadariaga requested changes

2023-02-08 09:11 UTC, mmadariaga commented on web/portal/platform/src/entities/AdministratorRelPublicEntity/SelectOptions.ts
> +            .name as string,
```suggestion
            .name,
```

2023-02-08 09:11 UTC, mmadariaga commented on web/portal/platform/src/entities/Brand/Brand.tsx
> +    required: true,
unnecessary

2023-02-08 09:11 UTC, mmadariaga commented on web/portal/platform/src/entities/Brand/Brand.tsx
> +    maxLength: 190,
unnecessary

2023-02-08 09:11 UTC, mmadariaga commented on web/portal/platform/src/entities/Brand/Brand.tsx
> +    required: true,
unnecessary

2023-02-08 09:11 UTC, mmadariaga commented on web/portal/platform/src/entities/Brand/Brand.tsx
> +    required: true,
unnecessary

2023-02-08 09:11 UTC, mmadariaga commented on web/portal/platform/src/entities/Brand/Brand.tsx
> +    $ref: '#/definitions/Feature',
Is this required?

2023-02-08 09:11 UTC, mmadariaga commented on web/portal/platform/src/entities/Brand/Brand.tsx
> +    enum: {
featires are array of integers. Why is this a enum?

2023-02-08 09:11 UTC, mmadariaga commented on web/portal/platform/src/entities/Brand/Brand.tsx
> +    enum: {
enum?

2023-02-08 09:11 UTC, mmadariaga commented on web/portal/platform/src/entities/Brand/Brand.tsx
> +    maxLength: 10,
unnecessary & maxLength is wrong

2023-02-08 09:11 UTC, mmadariaga commented on web/portal/platform/src/entities/Brand/Field/City.tsx
> +  return <>{(values.invoice as { [key: string]: string }).town}</>;
```suggestion
  return <>{(values.invoice as Record<string, string>).town}</>;
```

2023-02-08 09:13 UTC, mmadariaga commented on web/portal/platform/src/entities/Feature/SelectOptions.ts
> +        options.push({ id: item.id as string, label: item.iden as string });
I'll continue the review once you've fixed the issues above

2023-02-08 16:09 UTC, mmadariaga requested changes

2023-02-08 16:09 UTC, mmadariaga commented on web/portal/platform/src/entities/Brand/Field/PostalCode.tsx
> +const PostalCode: RouteTypeProps = (props): JSX.Element | null => {
In every custom component that doesn't return null:

```suggestion
const PostalCode: RouteTypeProps = (props): JSX.Element => {
```

2023-02-08 16:09 UTC, mmadariaga commented on web/portal/platform/src/router/useAclFilteredEntityMap.tsx
> +import { AboutMe, EntityAcl } from '../store/clientSession/aboutMe';
I don't think this is necessary

2023-02-09 08:05 UTC, mmadariaga approved these changes

2023-02-09 08:53 UTC, merged