web/portal: Added Service entity to platform portal
irontec/ivozprovider pull request #2022
Opened 2023-02-02 12:48 UTC by fmendozzac

#### Type Of Change 
- [ ] Small bug fix
- [x] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [x] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [x] Commits are split per component (schema, web/admin, kamusers, agis, ..)
- [x] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 
- [ ] Upport from existing Pull request #XXXX

#### Description
Added Service entity to platform portal

#### Additional information

2023-02-02 12:48 UTC, ironArt3mis commented
Rebase completed.

2023-02-02 14:45 UTC, mmadariaga requested changes

2023-02-02 14:45 UTC, mmadariaga commented on web/portal/platform/src/entities/Service/SelectOptions.ts
> +    (data) => {
```suggestion
    (data: EntityValues) => {
```

2023-02-02 14:45 UTC, mmadariaga commented on web/portal/platform/src/entities/Service/Service.tsx
> +  toStr: (row: EntityValues) => row.name as string,
```suggestion
  toStr: (row: ServicePropertyList<EntityValue>) => row.name as string,
```

2023-02-03 09:31 UTC, mmadariaga requested changes

2023-02-03 09:31 UTC, mmadariaga commented on web/portal/platform/src/entities/Service/SelectOptions/SelectOptions.ts
> +    (data) => {
Missing hint

2023-02-03 09:31 UTC, mmadariaga commented on web/portal/platform/src/entities/Service/SelectOptions/UnassignedServiceSelectOptions.ts
> +    (data) => {
Missing hint

2023-02-03 12:25 UTC, mmadariaga approved these changes

2023-02-06 01:03 UTC, merged