Added currency entity to platform portal
irontec/ivozprovider pull request #2034
Opened 2023-02-06 14:42 UTC by ironBatista

#### Type Of Change 
- [ ] Small bug fix
- [X] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [X] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [X] Commits are split per component (schema, web/admin, kamusers, agis, ..)
- [X] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 
- [ ] Upport from existing Pull request #XXXX

#### Description
This issue adds a new entity to the platform portal.

#### Additional information

2023-02-06 15:21 UTC, fmendozzac commented on web/portal/platform/src/entities/Currency/Form.tsx
> +      legend: _('Main'),
`legend: ' '`

2023-02-07 09:24 UTC, fmendozzac commented on web/portal/platform/src/entities/Currency/Form.tsx
> +      legend: _(''),
`legend: ''`

2023-02-07 10:19 UTC, fmendozzac approved these changes

2023-02-07 10:53 UTC, mmadariaga requested changes

2023-02-07 10:53 UTC, mmadariaga commented on web/portal/platform/.nvmrc
> +v14.20.0
remove or ignore this file

2023-02-07 11:45 UTC, mmadariaga approved these changes

2023-02-07 12:30 UTC, merged