web/portal: Added Active calls to platfom portal
irontec/ivozprovider pull request #2042
Opened 2023-02-07 15:02 UTC by fmendozzac

#### Type Of Change 
- [ ] Small bug fix
- [x] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [x] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [x] Commits are split per component (schema, web/admin, kamusers, agis, ..)
- [x] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 
- [ ] Upport from existing Pull request #XXXX

#### Description
Added Active calls entity to platfom portal

#### Additional information

2023-02-07 15:02 UTC, ironArt3mis commented
Rebase completed.

2023-02-08 09:19 UTC, mmadariaga requested changes

2023-02-08 09:19 UTC, mmadariaga commented on web/portal/platform/src/router/EntityMap.ts
> +      label: _('Calls'),
Active calls require a custom component and route. Check this out https://github.com/irontec/ivozprovider/blob/bleeding/web/portal/brand/src/router/addCustomRoutes.ts

2023-02-08 10:42 UTC, mmadariaga approved these changes

2023-02-08 11:21 UTC, merged