web/portal: Added Billable call to platform portal
irontec/ivozprovider pull request #2044
Opened 2023-02-07 16:16 UTC by fmendozzac

#### Type Of Change 
- [ ] Small bug fix
- [x] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [x] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [x] Commits are split per component (schema, web/admin, kamusers, agis, ..)
- [x] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 
- [ ] Upport from existing Pull request #XXXX

#### Description
Added Billable call entity to platform portal
#### Additional information

2023-02-07 16:16 UTC, ironArt3mis commented
Rebase completed.

2023-02-08 09:21 UTC, mmadariaga commented on web/portal/platform/src/entities/BillableCall/BillableCall.tsx
> +  toStr: (row: BillableCallPropertyList<EntityValue>) => row.id as string,
id is a umber actually
```suggestion
  toStr: (row: BillableCallPropertyList<EntityValue>) => row.id.toString(),
```

2023-02-08 10:43 UTC, mmadariaga requested changes

2023-02-08 10:43 UTC, mmadariaga commented on web/portal/platform/src/entities/BillableCall/BillableCall.tsx
> +    row.id?.toString() as string,
```suggestion
    row.id?.toString(),
```

2023-02-08 15:51 UTC, mmadariaga requested changes

2023-02-08 15:51 UTC, mmadariaga commented on web/portal/platform/src/entities/ProxyUser/ProxyUser.tsx
> +import SchemaIcon from '@mui/icons-material/Schema';
We've two different PRs mixed here

2023-02-09 11:17 UTC, merged