web/portal: Added ProxyUser to platform portal
irontec/ivozprovider pull request #2047
Opened 2023-02-08 11:20 UTC by fmendozzac

#### Type Of Change 
- [ ] Small bug fix
- [x] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [x] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [x] Commits are split per component (schema, web/admin, kamusers, agis, ..)
- [x] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 
- [ ] Upport from existing Pull request #XXXX

#### Description
Added ProxyUser entity to platform portal
#### Additional information

2023-02-08 11:21 UTC, ironArt3mis commented
Rebase completed.

2023-02-08 11:42 UTC, rbatistadev commented on web/portal/platform/src/entities/ProxyUser/SelectOptions.ts
> +        options.push({ id: item.id as string, label: item.name as string });
Could "item.id" be a value of a type number?

2023-02-08 11:44 UTC, rbatistadev requested changes
.

2023-02-09 11:18 UTC, mmadariaga approved these changes

2023-02-09 11:21 UTC, rbatistadev approved these changes

2023-02-09 11:29 UTC, merged