portal/platform: Added Porxy Trunks entity
irontec/ivozprovider pull request #2056
Opened 2023-02-09 12:52 UTC by rbatistadev

#### Type Of Change 
- [ ] Small bug fix
- [X] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [X] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [X] Commits are split per component (schema, web/admin, kamusers, agis, ..)
- [X] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 
- [ ] Upport from existing Pull request #XXXX

#### Description
Added Proxy Trunks entity

#### Additional information

2023-02-09 13:13 UTC, fmendozzac approved these changes

2023-02-09 16:04 UTC, mmadariaga requested changes

2023-02-09 16:04 UTC, mmadariaga commented on web/portal/platform/src/entities/ProxyTrunk/ProxyTrunk.tsx
>    title: _('Proxy Trunks', { count: 2 }),
```suggestion
  title: _('Proxy Trunk', { count: 2 }),
```

2023-02-09 16:04 UTC, mmadariaga commented on web/portal/platform/src/entities/ProxyTrunk/SelectOptions.ts
> -import { DropdownChoices, EntityValues } from '@irontec/ivoz-ui';
why?

2023-02-10 11:55 UTC, mmadariaga approved these changes

2023-02-13 08:41 UTC, merged