portal/brand: remove create, delete & update actons from CompanyBalance
irontec/ivozprovider pull request #2088
Opened 2023-02-23 17:05 UTC by fmendozzac

#### Type Of Change 
- [X] Small bug fix
- [ ] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [X] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [X] Commits are split per component (schema, web/admin, kamusers, agis, ..)
- [X] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 
- [ ] Upport from existing Pull request #XXXX

#### Description
remove create, delete & update actons from CompanyBalance

#### Additional information

2023-02-23 17:05 UTC, ironArt3mis commented
Rebase completed.

2023-02-23 20:39 UTC, mmadariaga requested changes

2023-02-23 20:39 UTC, mmadariaga commented on web/portal/brand/src/entities/CompanyBalances/CompanyBalances.tsx
> +    iden: 'Prepaid Balance',
This is used check out if a restricted admin can access this entity. It must be a valid ACL iden (fetched when you call /my/profile). So:
```suggestion
    iden: 'Companies',
```

2023-02-24 10:50 UTC, mmadariaga approved these changes

2023-02-24 10:57 UTC, merged