portal/client: fix holidayNumberCountry in ExternalCallFilter
irontec/ivozprovider pull request #2094
Opened 2023-02-24 13:04 UTC by fmendozzac

#### Type Of Change 
- [x] Small bug fix
- [ ] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [x] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [x] Commits are split per component (schema, web/admin, kamusers, agis, ..)
- [x] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 
- [ ] Upport from existing Pull request #XXXX

#### Description
fix holidayNumberCountry in ExternalCallFilter

#### Additional information

2023-02-24 13:05 UTC, ironArt3mis commented
Rebase completed.

2023-02-27 07:39 UTC, mmadariaga requested changes

2023-02-27 07:39 UTC, mmadariaga commented on web/portal/client/src/entities/Country/Country.tsx
> +  toStr: (row: CountryPropertyList<EntityValue>) => row.countryCode as string,
Country must show country code or name depending on the entity is using it. You'll have to create another SelectOptions to handle this

2023-02-27 09:34 UTC, mmadariaga approved these changes

2023-02-27 09:49 UTC, merged