Portal platform proxy trunk name field should be editable with ids different to 1
irontec/ivozprovider pull request #2202
Opened 2023-03-23 10:30 UTC by rbatistadev

#### Type Of Change 
- [X] Small bug fix
- [ ] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [X] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [X] Commits are split per component (schema, web/admin, kamusers, agis, ..)
- [X] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 
- [ ] Upport from existing Pull request #XXXX

#### Description

#### Additional information

2023-03-24 15:51 UTC, mmadariaga approved these changes

2023-03-24 16:16 UTC, rbatistadev commented on web/portal/platform/src/entities/ProxyTrunk/Form.tsx
> +    name: row?.id === 1 || false,
finished

2023-03-28 06:11 UTC, mmadariaga requested changes

2023-03-28 06:11 UTC, mmadariaga commented on web/rest/platform/config/api/raw/provider.yml
> +        raw: "id === 1"
add tests

2023-03-29 08:10 UTC, mmadariaga requested changes

2023-03-31 07:41 UTC, mmadariaga approved these changes

2023-04-03 05:20 UTC, merged