portal/platform: Updated translations in all languages
irontec/ivozprovider pull request #2268
Opened 2023-06-19 07:32 UTC by Kaian

#### Type Of Change 
- [ ] Small bug fix
- [X] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [X] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [X] Commits are split per component (schema, web/admin, kamusers, agis, ..)
- [ ] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 
- [ ] Upport from existing Pull request #XXXX

#### Description
Updated translations in all supported four languages for new platform portal.

#### Additional information

2023-06-19 08:05 UTC, mmadariaga requested changes

2023-06-19 08:05 UTC, mmadariaga commented on web/portal/platform/src/translations/es.json
> +  "Residential Device_other": "Dispositivo residencial",
plural

2023-06-19 08:35 UTC, Kaian commented on web/portal/platform/src/translations/es.json
> +  "Residential Device_other": "Dispositivo residencial",
Updated!

2023-06-20 14:34 UTC, mmadariaga approved these changes

2023-06-22 10:34 UTC, merged