Back extensions section alias import
irontec/ivozprovider pull request #2382
Opened 2023-09-19 11:03 UTC by rbatistadev

#### Type Of Change 
- [ ] Small bug fix
- [X] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [X] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [X] Commits are split per component (schema, web/admin, kamusers, agis, ..)
- [X] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 
- [ ] Upport from existing Pull request #XXXX

#### Description

#### Additional information

2023-09-20 06:26 UTC, mmadariaga requested changes

2023-09-20 06:26 UTC, mmadariaga commented on web/rest/client/config/routes.yaml
> +  path: '/extensions/mass_import'
missing tests

2023-09-21 06:46 UTC, mmadariaga requested changes

2023-09-21 06:46 UTC, mmadariaga commented on library/Ivoz/Provider/Domain/Service/Extension/ExtensionFactory.php
> +                    substr($countryPrefix, 1)
NumberCountry is a foreign key to Country table. You'll have to map country prefix to it's pk

2023-09-21 06:46 UTC, mmadariaga commented on library/phpstan-baseline.neon
> +			message: "#^Parameter \\#1 \\$haystack of function str_contains expects string, array\\|string given\\.$#"
You can fix this

2023-09-21 06:46 UTC, mmadariaga commented on web/rest/client/features/provider/extension/postExtension.feature
> +    """
Retrieve created extensions to ensure everything is fine

2023-09-21 06:46 UTC, mmadariaga commented on web/rest/client/src/Controller/Provider/PostExtensionsMassImportAction.php
> +        if (!$company->getBrand()) {
Company has always a brand

2023-09-21 06:46 UTC, mmadariaga commented on web/rest/client/src/Controller/Provider/PostExtensionsMassImportAction.php
> +        $calendarId = $request->request->get('calendar');
calendar?

2023-09-21 06:46 UTC, mmadariaga commented on web/rest/client/src/Model/ExtensionsMassImport.php
> +        int $imported
```suggestion
        int $failed
```

2023-09-21 14:31 UTC, mmadariaga requested changes

2023-09-21 14:31 UTC, mmadariaga commented on library/Ivoz/Provider/Domain/Service/Extension/ExtensionFactory.php
> +                ->findOneByCountryCode($countryCode);
You'll need to use both, CountryPrefix and CountryCode (This one is optional is the csv) ir order to resolve the country.

CSV example:
```
Extension,CountryPrefix,Number,CountryCode
200,+34,944048184,ES
201,+34,944048185,ES
202,+34,944048186
203,+1,944048187
204,+1,944048188,US
```

Countries in db:
```
mysql> select id, code, name_en, countryCode from Countries where countryCode = '+1';
+-----+------+--------------------------------------+-------------+
| id  | code | name_en                              | countryCode |
+-----+------+--------------------------------------+-------------+
|  38 | CA   | Canada                               | +1          |
| 184 | PR   | Puerto Rico                          | +1          |
| 234 | UM   | United States Minor Outlying Islands | +1          |
| 235 | US   | United States of America             | +1          |
+-----+------+--------------------------------------+-------------+
4 rows in set (0,00 sec)
```

2023-09-21 14:33 UTC, mmadariaga commented on web/rest/client/features/provider/extension/postExtensionMassImport.feature
> +              "numberCountry": null,
should this throw an error?

2023-09-21 15:50 UTC, rbatistadev commented on web/rest/client/features/provider/extension/postExtensionMassImport.feature
> +              "numberCountry": null,
No it should not.

2023-09-22 10:32 UTC, mmadariaga requested changes

2023-09-22 10:32 UTC, mmadariaga commented on library/Ivoz/Provider/Application/Service/Extension/SyncFromCsv.php
> +                    user: null
don't set user as it's always null

2023-09-22 10:32 UTC, mmadariaga commented on library/Ivoz/Provider/Application/Service/User/SyncFromCsv.php
> +                        null
Don't set null values. they are not required

2023-09-22 10:32 UTC, mmadariaga commented on library/spec/Ivoz/Provider/Application/Service/User/SyncFromCsvSpec.php
>              )
unnecessary

2023-09-22 10:32 UTC, mmadariaga commented on web/rest/client/config/api/resources.yml
> +            description: "*extension, *country prefix, number, country code"
```suggestion
            description: "*extension, *country prefix, *number, country code"
```

2023-09-25 07:44 UTC, mmadariaga requested changes

2023-09-25 07:44 UTC, mmadariaga commented on library/Ivoz/Provider/Application/Service/Extension/SyncFromCsv.php
> +                    number: $number,
Dont' mix named arguments and classic arguments

2023-09-25 09:22 UTC, mmadariaga approved these changes

2023-09-25 09:23 UTC, merged