core: update scripts with automatic app discovery loops
irontec/ivozprovider pull request #2408
Opened 2023-10-24 14:12 UTC by Kaian

#### Type Of Change 
- [ ] Small bug fix
- [X] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [X] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [X] Commits are split per component (schema, web/admin, kamusers, agis, ..)
- [X] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 
- [ ] Upport from existing Pull request #XXXX

#### Description

#### Additional information

2023-10-25 07:18 UTC, Kaian commented on library/bin/test-psalm
> +APPS=$(find /opt/irontec/ivozprovider -name composer.json ! -path '*/vendor/*' ! -path '*/composer-packages/*' ! -path "*/agi/*" ! -path "*/schema/*" ! -path "*/realtime/*" -printf "%h\n")
psalm is not executed in following apps:

- schema
- microservices/realtime
- asterisk/agi

2023-10-25 07:18 UTC, Kaian commented on library/bin/test-phpstan
> +APPS=$(find $HOME -name composer.json ! -path '*/vendor/*' ! -path '*/composer-packages/*' ! -path "*/schema/*" -printf "%h\n")
phpstan is not executed in schema app

2023-10-25 09:40 UTC, mmadariaga requested changes

2023-10-25 09:40 UTC, mmadariaga commented on library/bin/composer-require
> +APPS=$(find /opt/irontec/ivozprovider -name composer.json ! -path '*/vendor/*' ! -path '*/composer-packages/*' -printf "%h\n")
exclude library

2023-10-25 09:40 UTC, mmadariaga commented on library/bin/test-phpstan
> +APPS=$(find $HOME -name composer.json ! -path '*/vendor/*' ! -path '*/composer-packages/*' ! -path "*/schema/*" -printf "%h\n")
🤔

2023-10-25 10:05 UTC, Kaian commented on library/bin/composer-require
> +APPS=$(find /opt/irontec/ivozprovider -name composer.json ! -path '*/vendor/*' ! -path '*/composer-packages/*' -printf "%h\n")
Good catch!

2023-10-25 10:26 UTC, Kaian commented on library/bin/composer-require
> +APPS=$(find /opt/irontec/ivozprovider -name composer.json ! -path '*/vendor/*' ! -path '*/composer-packages/*' -printf "%h\n")
Updated

2023-10-30 07:20 UTC, mmadariaga approved these changes

2023-11-07 08:59 UTC, merged