Endpoints to retrieve realtime filter actions
irontec/ivozprovider pull request #2416
Opened 2023-11-13 17:24 UTC by rbatistadev

#### Type Of Change 
- [ ] Small bug fix
- [X] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [X] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [X] Commits are split per component (schema, web/admin, kamusers, agis, ..)
- [X] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 
- [ ] Upport from existing Pull request #XXXX

#### Description
Created four new endpoints to retrieve filter actions for future use in Redis 

#### Additional information

2023-11-14 14:19 UTC, mmadariaga requested changes

2023-11-14 14:19 UTC, mmadariaga commented on web/rest/brand/config/api/resources.yml
> +          description: 'Brand Id'
brand API souldn't accept brand id

2023-11-14 14:19 UTC, mmadariaga commented on web/rest/brand/src/Controller/My/ActiveCallsRealtimeFilterAction.php
> +        $brandId = $request->query->get('b');
get from user

2023-11-14 14:19 UTC, mmadariaga commented on web/rest/brand/src/Controller/My/ActiveCallsRealtimeFilterAction.php
> +        }
Extract into application service

2023-11-14 14:19 UTC, mmadariaga commented on web/rest/client/config/api/resources.yml
> +            description: 'Carrier Id'
wrong filters for client API

2023-11-14 14:19 UTC, mmadariaga commented on web/rest/client/src/Controller/My/ActiveCallsRealtimeFilterAction.php
> +        ];
extract into app service

2023-11-14 14:19 UTC, mmadariaga commented on web/rest/platform/config/api/resources.yml
> +          - name: b
some filters are missing

2023-11-14 14:19 UTC, mmadariaga commented on web/rest/platform/src/Controller/My/ActiveCallsRealtimeFilterAction.php
> +        ];
extract

2023-11-16 10:07 UTC, mmadariaga requested changes

2023-11-16 10:07 UTC, mmadariaga commented on library/Ivoz/Provider/Application/Service/ActiveCall/RegistrationChannelResolver.php
> +    public function getDefaultCriteria(array $tokenPayload): array
Services can only have one public method

2023-11-16 10:07 UTC, mmadariaga commented on web/rest/platform/src/Controller/My/ActiveCallsRealtimeFilterAction.php
> +            'dp' => (int)$ddiProviderId
```suggestion
            'b' => (int) $brandId,
            'c' => (int) $companyId,
            'cr' => (int) $carrierId,
            'dp' => (int) $ddiProviderId
```

2023-11-16 10:56 UTC, rbatistadev commented on web/rest/platform/config/api/resources.yml
> +            description: 'DdiProvider Id'
Set inbound and outbound as new query arguments for direction

2023-11-16 14:39 UTC, mmadariaga commented
Add API tests and you're done

2023-11-20 15:59 UTC, mmadariaga approved these changes

2023-11-21 08:44 UTC, merged