Operator panel feature
irontec/ivozprovider pull request #2418
Opened 2023-11-16 12:27 UTC by mmadariaga

#### Type Of Change 
- [ ] Small bug fix
- [X] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [X] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [X] Commits are split per component (schema, web/admin, kamusers, agis, ..)
- [X] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 
- [ ] Upport from existing Pull request #XXXX

#### Description

#### Additional information

2023-11-16 15:28 UTC, Kaian requested changes

2023-11-16 16:59 UTC, mmadariaga commented on library/Ivoz/Provider/Domain/Service/FeaturesRelCompany/CheckValidity.php
> +}
good catch

2023-11-16 16:59 UTC, mmadariaga commented on schema/DoctrineMigrations/Version20231115173418.php
> +                    "pannello operatore"
:+1:

2023-11-17 12:03 UTC, Kaian approved these changes

2023-11-17 16:23 UTC, merged