PROVIDER-1644: dashboard icons
irontec/ivozprovider pull request #2530
Opened 2024-02-27 13:38 UTC by SbenIrontec

#### Type Of Change 
- [ ] Small bug fix
- [ ] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [ ] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [ ] Commits are split per component (schema, web/admin, kamusers, agis, ..)
- [ ] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 
- [ ] Upport from existing Pull request #XXXX

#### Description

#### Additional information

2024-02-29 08:57 UTC, Kaian commented
- Assign the PR to Soraya
- Set milestone information based on PROVIDER-1644 fixed version
- Set labels *tempest*,*enhancement*,*portal/platform*,*portal/brand*,*portal/client*, *portal/user*
- Set reviewer based on Tech Reviewer on PROVIDER-1644

2024-03-04 09:50 UTC, mmadariaga requested changes

2024-03-04 09:50 UTC, mmadariaga commented on web/portal/client/src/components/Dashboard/cards/CardsAmountVpbx.tsx
> -import { DashboardData } from '../@types';
this is required

2024-03-04 09:50 UTC, mmadariaga commented on web/portal/client/src/components/Dashboard/cards/CardsAmountVpbx.tsx
> +import DialpadIcon from '../DialpadIcon';
There are actually four client portals, based on loged in client type (vpbx, retail, residential and wholesale). This change must be applied to CardsAmountResidential.tsx, CardsAmountRetail.tsx and CardsAmountWholeSale.tsx as well. 

I guess that IconClients, IconPlatforms and IconUsers are no longer needed so remove them.

2024-03-04 09:50 UTC, mmadariaga commented on web/portal/brand/src/components/Dashboard/Dashboard.tsx
> -import IconPlatformsDashboard from './IconPlatforms';
Remove old icons

2024-03-04 09:50 UTC, mmadariaga commented on web/portal/platform/src/components/Dashboard/Dashboard.tsx
> -import IconUsersDashboard from './IconUsers';
Remove old clients

2024-03-04 09:50 UTC, mmadariaga commented on web/portal/user/src/components/Dashboard/Dashboard.tsx
> -import PhoneForwardedIcon from './PhoneForwardedIcon';
Remove old icons

2024-03-06 10:05 UTC, mmadariaga approved these changes

2024-03-06 10:17 UTC, merged