Add option to resend fax
irontec/ivozprovider pull request #2605
Opened 2024-04-05 13:07 UTC by R0MANDEV

#### Type Of Change 
- [x] Small bug fix
- [x] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [x] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [x] Commits are split per component (schema, web/admin, kamusers, agis, ..)
- [x] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 
- [ ] Upport from existing Pull request #XXXX

#### Description

#### Additional information

2024-04-09 06:54 UTC, mmadariaga requested changes

2024-04-09 06:54 UTC, mmadariaga commented on web/portal/client/src/translations/es.json
> +  "Resend faxes": "Reenviar faxs",
faxs

2024-04-09 06:54 UTC, mmadariaga commented on web/portal/client/src/translations/es.json
> +  "Resend faxes?": "Reenviar faxs?",
faxs

2024-04-09 06:54 UTC, mmadariaga commented on web/portal/client/src/translations/es.json
> +  "You are about to resend this faxes": "Está a punto de reenviar este faxs.",
faxs

2024-04-09 06:54 UTC, mmadariaga commented on web/portal/client/src/entities/FaxesOut/Action/index.ts
> +  Regenerate: {
```suggestion
  Resend: {
```

2024-04-09 06:54 UTC, mmadariaga commented on web/portal/client/src/entities/FaxesOut/Action/Resend.tsx
> +          {_('Resend faxes')}
```suggestion
          {_('Resend fax')}
```
it's singular

2024-04-09 06:54 UTC, mmadariaga commented on web/portal/client/src/entities/FaxesOut/Action/Resend.tsx
> +          title={_('Resend faxes')}
```suggestion
          title={_('Resend fax')}
```

2024-04-09 06:54 UTC, mmadariaga commented on web/portal/client/src/entities/FaxesOut/Action/Resend.tsx
> +        <DialogTitle id='alert-dialog-title'>{_('Resend faxes?')}</DialogTitle>
```suggestion
        <DialogTitle id='alert-dialog-title'>{_('Resend fax?')}</DialogTitle>
```

2024-04-09 06:54 UTC, mmadariaga commented on web/portal/client/src/entities/FaxesOut/Action/Resend.tsx
> +            {_('You are about to resend this faxes')}
```suggestion
            {_('You are about to resend this fax')}
```

2024-04-09 06:54 UTC, mmadariaga commented on web/portal/client/src/entities/FaxesOut/Action/Resend.tsx
> +          <OutlinedButton onClick={handleClose}>Cancel</OutlinedButton>
`Cancel` should be translatable

2024-04-09 14:00 UTC, mmadariaga approved these changes

2024-04-09 14:26 UTC, Kaian commented on web/portal/client/src/translations/es.json
> +  "Resend fax?": "Reenviar fax?",
Missing ¿ symbol for spanish questions

2024-04-10 09:17 UTC, Kaian approved these changes

2024-04-10 09:17 UTC, merged