Select multiple entities and do a bulk edit
irontec/ivozprovider pull request #2632
Opened 2024-04-22 10:35 UTC by R0MANDEV

#### Type Of Change 
- [x] Small bug fix
- [x] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [x] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [x] Commits are split per component (schema, web/admin, kamusers, agis, ..)
- [x] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 
- [ ] Upport from existing Pull request #XXXX

#### Description
Select multiple entities and do a bulk edit

#### Additional information

2024-04-23 09:15 UTC, mmadariaga requested changes

2024-04-23 09:15 UTC, mmadariaga commented on web/portal/platform/src/entities/AdministratorRelPublicEntity/Action/RevokeAll.tsx
> +  const admId =
same here

2024-04-23 11:03 UTC, mmadariaga approved these changes

2024-04-24 16:04 UTC, mmadariaga requested changes

2024-04-24 16:04 UTC, mmadariaga commented on web/portal/brand/src/entities/AdministratorRelPublicEntity/Action/RevokeAll.tsx
> +      .catch((error: Record<string, any>) => {
```suggestion
      .catch((error: ApiError) => {
```
Defined in ivoz-ui/services/api/ApiClient.ts

2024-04-24 16:04 UTC, mmadariaga commented on web/portal/platform/src/entities/AdministratorRelPublicEntity/Action/GrantAll.tsx
> +      .catch((error: Record<string, any>) => {
```suggestion
      .catch((error: ApiError) => {
```

2024-04-24 16:04 UTC, mmadariaga commented on web/portal/platform/src/entities/AdministratorRelPublicEntity/Action/GrantAll.tsx
> +            window.location.reload();
use `store.list.reload()`

2024-04-24 16:04 UTC, mmadariaga commented on web/portal/platform/src/entities/AdministratorRelPublicEntity/Action/GrantReadOnly.tsx
> +            window.location.reload();
use `store.list.reload()`

2024-04-24 16:04 UTC, mmadariaga commented on web/portal/platform/src/entities/AdministratorRelPublicEntity/Action/GrantReadOnly.tsx
> +      .catch((error: Record<string, any>) => {
```suggestion
      .catch((error: ApiError) => {
```

2024-04-24 16:04 UTC, mmadariaga commented on web/portal/platform/src/entities/AdministratorRelPublicEntity/Action/RevokeAll.tsx
> +            window.location.reload();
same here

2024-04-24 16:04 UTC, mmadariaga commented on web/portal/platform/src/entities/AdministratorRelPublicEntity/Action/RevokeAll.tsx
> +      .catch((error: Record<string, any>) => {
same here

2024-04-26 07:19 UTC, mmadariaga approved these changes

2024-04-26 07:23 UTC, Kaian requested changes

2024-04-26 07:23 UTC, Kaian commented on web/portal/brand/src/translations/es.json
> +  "Grant Write Access": "Acceso de escriptura",
_Acceso de escritura_

2024-04-26 07:23 UTC, Kaian commented on web/portal/platform/src/translations/ca.json
> +  "Accept": "AcceptarWhite",
AcceptarWhite?

2024-04-26 07:23 UTC, Kaian commented on web/portal/platform/src/translations/es.json
> +  "Grant Write Access": "Acceso de escriptura",
escritura

2024-04-26 07:59 UTC, Kaian commented on web/portal/platform/src/translations/ca.json
> +  "Accept": "AcceptarWhite",
You have included this platform portal change in a commit tagged as portal/brand

2024-04-26 07:59 UTC, Kaian commented on web/portal/platform/src/translations/es.json
> +  "Grant Write Access": "Acceso de escriptura",
You have included this platform portal change in a commit tagged as portal/brand

2024-04-26 09:37 UTC, Kaian commented
Code is not properly split in commits.

portal/brand commit contains changes that belongs to portal/platform.

2024-04-30 11:16 UTC, Kaian approved these changes

2024-05-06 08:55 UTC, merged