Add residential devices ruri domain field
irontec/ivozprovider pull request #2641
Opened 2024-04-29 15:28 UTC by danigargar

Added R-URI fiel to Residential devices, Retail devices and Firends

#### Type Of Change 
- [ ] Small bug fix
- [ ] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [ ] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [ ] Commits are split per component (schema, web/admin, kamusers, agis, ..)
- [ ] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 
- [ ] Upport from existing Pull request #XXXX

#### Description

#### Additional information

2024-04-30 10:03 UTC, mmadariaga requested changes

2024-04-30 10:03 UTC, mmadariaga commented on library/Ivoz/Provider/Domain/Model/Friend/Friend.php
> +            throw new \DomainException('R-URI or IP + port must be provided');
Shouldn't this all validations be within `if (isDirectConnectivity)`?

2024-04-30 10:16 UTC, danigargar commented on web/rest/client/features/provider/friend/postFriend.feature
> +          "ruriDomain": null,
ruriDomain is null beacause directConnectivity is intervpbx. ruriDomain may be not null only when directConnectivity is "yes".

2024-05-02 06:45 UTC, mmadariaga requested changes

2024-05-02 06:45 UTC, mmadariaga commented on web/rest/client/features/provider/retailAccount/putRetailAccount.feature
> +  Scenario: Update a retail account
You've two `Scenario: Update a retail account` in this file. How are they different from each other? Put it in scenario description

2024-05-03 11:03 UTC, mmadariaga approved these changes

2024-05-08 16:43 UTC, cruzccl approved these changes

2024-05-09 05:59 UTC, merged