Show user related voicemails
irontec/ivozprovider pull request #2643
Opened 2024-04-30 15:28 UTC by danigargar

#### Type Of Change 
- [ ] Small bug fix
- [x] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [x] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [x] Commits are split per component (schema, web/admin, kamusers, agis, ..)
- [x] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 
- [ ] Upport from existing Pull request #XXXX

#### Description

#### Additional information

2024-05-03 11:17 UTC, mmadariaga requested changes

2024-05-03 11:17 UTC, mmadariaga commented on library/Ivoz/Provider/Infrastructure/Persistence/Doctrine/VoicemailRelUserDoctrineRepository.php
> +        );
You can make this easier
```suggestion
        $result = $qb
            ->getQuery()
            ->getScalarResult();

        return array_map(
            function ($row): int {
                return (int) $row['voicemailId'];
            },
            $result
        );
```

2024-05-06 07:08 UTC, Kaian commented
Remove the internal jira code from the pull request title ;-)

2024-05-13 13:40 UTC, mmadariaga approved these changes

2024-05-15 08:46 UTC, ironArt3mis requested changes
Functional review required

2024-05-16 16:25 UTC, cruzccl approved these changes

2024-05-16 16:30 UTC, ironArt3mis approved these changes

2024-05-17 06:00 UTC, merged