Direct connectivity clients must have socket
irontec/ivozprovider pull request #2646
Opened 2024-05-03 10:12 UTC by danigargar

#### Type Of Change 
- [ ] Small bug fix
- [x] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [x] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [x] Commits are split per component (schema, web/admin, kamusers, agis, ..)
- [x] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 
- [ ] Upport from existing Pull request #XXXX

#### Description

#### Additional information

2024-05-14 08:00 UTC, mmadariaga requested changes

2024-05-15 06:07 UTC, danigargar commented on web/portal/brand/src/translations/es.json
> +  "Proxy user": "Proxy User",
Did you mean "Proxy User_other"?

2024-05-15 07:12 UTC, mmadariaga requested changes

2024-05-15 07:12 UTC, mmadariaga commented on web/portal/brand/src/translations/en.json
> +  "Proxy user": "Proxy User",
remove this key and use `Proxy User`

2024-05-15 08:04 UTC, Kaian approved these changes

2024-05-15 13:10 UTC, ironArt3mis requested changes
Functional review required

2024-05-16 07:17 UTC, mmadariaga approved these changes

2024-05-17 12:36 UTC, ironArt3mis approved these changes

2024-05-17 12:47 UTC, ironArt3mis approved these changes

2024-05-17 12:47 UTC, merged