Limit access to user voicemails in client
irontec/ivozprovider pull request #2663
Opened 2024-05-23 09:47 UTC by danigargar

Client administration access to a user's voicemail messages has been banned.

#### Type Of Change 
- [ ] Small bug fix
- [x] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [x] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [x] Commits are split per component (schema, web/admin, kamusers, agis, ..)
- [x] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 
- [ ] Upport from existing Pull request #XXXX

#### Description

#### Additional information

2024-05-23 10:27 UTC, ironArt3mis requested changes
Functional review required

2024-05-23 14:59 UTC, mmadariaga requested changes

2024-05-23 14:59 UTC, mmadariaga commented on web/portal/client/src/entities/Voicemail/Voicemail.tsx
> +    if (false && row.user !== null) {
```suggestion
    if (false && ...
```

2024-05-24 11:40 UTC, cruzccl approved these changes

2024-05-24 11:47 UTC, ironArt3mis approved these changes

2024-05-24 11:48 UTC, merged