Provider 1830 manage friends from brand portal
irontec/ivozprovider pull request #2666
Opened 2024-05-27 15:36 UTC by danigargar

#### Type Of Change 
- [ ] Small bug fix
- [X] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [X] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [X] Commits are split per component (schema, web/admin, kamusers, agis, ..)
- [X] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 
- [ ] Upport from existing Pull request #XXXX

#### Description

#### Additional information

2024-05-28 07:37 UTC, ironArt3mis requested changes
Functional review required

2024-06-03 09:13 UTC, mmadariaga requested changes

2024-06-03 09:13 UTC, mmadariaga commented on web/portal/brand/src/entities/Friend/hooks/useIntercompanyId.tsx
> +    setInterCompany([]);
An array is not a `Record<number, string>`

2024-06-03 09:13 UTC, mmadariaga commented on web/portal/brand/src/entities/Friend/hooks/useIntercompanyId.tsx
> +          setInterCompany(options || []);
Beware the types

2024-06-03 09:13 UTC, mmadariaga commented on web/rest/brand/features/provider/friend/postFriend.feature
> +    Given I add Authorization header
Unnecessary I guess

2024-06-03 09:13 UTC, mmadariaga commented on web/rest/brand/src/Controller/Provider/CompaniesByCorporateUnassignedAction.php
> +        return $response;
It would be nice to extract this into an application service

2024-06-03 09:20 UTC, danigargar commented on web/portal/brand/src/entities/Friend/Field/StatusIcon.tsx
> +  //@TODO POSPONED else RegisterStatus::getLocationStatus
Copy/paste from web/portal/client/src/entities/Friend/Field/StatusIcon.tsx

I remove it here.

2024-06-03 13:38 UTC, mmadariaga approved these changes

2024-06-10 13:39 UTC, cruzccl approved these changes

2024-06-10 13:44 UTC, ironArt3mis approved these changes

2024-06-10 13:48 UTC, merged