Updated translations
irontec/ivozprovider pull request #2705
Opened 2024-07-24 08:39 UTC by rbatistadev

#### Type Of Change 
- [X] Small bug fix
- [ ] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [X] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [X] Commits are split per component (schema, portal/platform, kamusers, agis, ..)
- [X] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 
- [ ] Upport from existing Pull request #XXXX

#### Description
- Modified translations for update Calendar Period meaning

#### Additional information

2024-07-24 08:47 UTC, ironArt3mis requested changes
Functional review required

2024-07-24 11:52 UTC, danigargar requested changes

2024-07-24 11:52 UTC, danigargar commented on web/portal/client/src/translations/ca.json
> +  "Calendar Period_one": "Horario Especiale",
"Horari Especial"

2024-07-26 06:15 UTC, danigargar approved these changes

2024-07-26 09:38 UTC, danigargar approved these changes

2024-07-29 11:16 UTC, ironArt3mis approved these changes

2024-07-30 06:22 UTC, merged