Show company on user list
irontec/ivozprovider pull request #2710
Opened 2024-07-26 11:05 UTC by danigargar

#### Type Of Change 
- [x] Small bug fix
- [ ] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [x] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [x] Commits are split per component (schema, portal/platform, kamusers, agis, ..)
- [x] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 
- [ ] Upport from existing Pull request #XXXX

#### Description

#### Additional information

2024-07-26 11:29 UTC, ironArt3mis requested changes
Functional review required

2024-07-27 11:23 UTC, rbatistadev commented on web/rest/brand/features/provider/webPortal/getWebPortal.feature
> +              "company": null
I suggest this should be tested

2024-07-27 11:23 UTC, rbatistadev commented on web/rest/brand/features/provider/webPortal/getWebPortal.feature
> +              "company": null
I suggest this should be tested

2024-07-27 11:24 UTC, rbatistadev commented on web/portal/brand/src/entities/WebPortal/WebPortal.tsx
>      iden: 'WebPortals',
Cypress test for this please

2024-07-30 12:11 UTC, rbatistadev approved these changes

2024-08-01 13:03 UTC, merged