Added WebPortal children to each client type
irontec/ivozprovider pull request #2731
Opened 2024-08-19 09:05 UTC by danigargar

#### Type Of Change 
- [ ] Small bug fix
- [x] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [x] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [x] Commits are split per component (schema, portal/platform, kamusers, agis, ..)
- [x] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 
- [ ] Upport from existing Pull request #XXXX

2024-08-19 12:18 UTC, ironArt3mis requested changes
Functional review required

2024-08-20 08:02 UTC, rbatistadev commented on web/portal/brand/cypress/e2e/Clients/Residential/Residentials.cy.js
> +  ///////////////////////
```suggestion
  ///////////////////////
  // POST
  ///////////////////////
```

2024-08-20 08:03 UTC, rbatistadev commented on web/portal/brand/cypress/e2e/Clients/Retails/Retails.cy.js
> +  ///////////////////////
```suggestion
  ///////////////////////
  // POST
  ///////////////////////
```

2024-08-20 08:05 UTC, rbatistadev commented on web/portal/brand/cypress/e2e/Clients/VirtualPbxs/VirtualPbxs.cy.js
> +  ///////////////////////
```suggestion
  ///////////////////////
  // POST
  ///////////////////////
```

2024-08-21 07:45 UTC, ironArt3mis approved these changes

2024-08-21 07:51 UTC, merged