Update dependencies
irontec/ivozprovider pull request #2746
Opened 2024-08-30 08:42 UTC by rbatistadev

#### Type Of Change 
- [X] Small bug fix
- [ ] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [X] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [X] Commits are split per component (schema, portal/platform, kamusers, agis, ..)
- [X] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 
- [ ] Upport from existing Pull request #XXXX

#### Description
Updated ivoz-dev-tools dependencies

#### Additional information

2024-08-30 10:26 UTC, ironArt3mis requested changes
Functional review required

2024-08-30 10:39 UTC, danigargar requested changes

2024-08-30 10:39 UTC, danigargar commented on library/Ivoz/Provider/Domain/Model/Administrator/AdministratorSecurityTrait.php
This is not autogenerated. Use a separate commit, please

2024-08-30 10:39 UTC, danigargar commented on library/composer.lock
Why there are no changes to composer.json?

2024-08-30 20:23 UTC, rbatistadev commented on library/composer.lock
because there is a mask in composer.json, something like irontec/ivoz-dev-tools:^5.3

2024-09-02 06:15 UTC, danigargar approved these changes

2024-09-04 10:13 UTC, danigargar approved these changes

2024-09-04 10:45 UTC, ironArt3mis approved these changes

2024-09-04 10:53 UTC, merged