Portal brand notification templates filter notification types based on enabled features
irontec/ivozprovider pull request #2747
Opened 2024-09-02 10:39 UTC by rbatistadev

#### Type Of Change 
- [ ] Small bug fix
- [X] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [X] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [X] Commits are split per component (schema, portal/platform, kamusers, agis, ..)
- [X] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 
- [ ] Upport from existing Pull request #XXXX

#### Description
Filter notification types based on enabled features

#### Additional information

2024-09-02 10:44 UTC, ironArt3mis requested changes
Functional review required

2024-09-02 12:49 UTC, danigargar approved these changes

2024-09-03 08:39 UTC, cruzccl approved these changes

2024-09-03 08:43 UTC, ironArt3mis approved these changes

2024-09-03 08:50 UTC, merged