Enable or disable the Impersonate feature
irontec/ivozprovider pull request #2768
Opened 2024-09-13 12:21 UTC by R0MANDEV

#### Type Of Change 
- [x] Small bug fix
- [x] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [x] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [x] Commits are split per component (schema, portal/platform, kamusers, agis, ..)
- [ ] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 
- [ ] Upport from existing Pull request #XXXX

#### Description

#### Additional information

2024-09-16 16:32 UTC, ironArt3mis requested changes
Functional review required

2024-09-23 16:00 UTC, danigargar requested changes
1) Put cypress tests and pacts on its own commit.
2) Why no tests for platform?

2024-09-23 16:00 UTC, danigargar commented on web/portal/brand/src/entities/Administrator/Action/Impersonate.tsx
> +  const isCanImpersonate = !profile?.canImpersonate;
```suggestion
  const canImpersonate = !profile?.canImpersonate;
```

2024-09-23 16:00 UTC, danigargar commented on web/portal/brand/src/entities/Company/Action/Impersonate.tsx
> +  const isCanImpersonate = !profile?.canImpersonate;
idem

2024-09-23 16:00 UTC, danigargar commented on web/portal/platform/src/entities/Administrator/Action/Impersonate.tsx
> +  const isCanImpersonate = !profile?.canImpersonate;
idem

2024-09-23 16:00 UTC, danigargar commented on web/portal/platform/src/entities/Brand/Action/Impersonate.tsx
> +  const isCanImpersonate = !profile?.canImpersonate;
idem

2024-09-24 10:22 UTC, R0MANDEV commented
1.- files sorted by commit
2.- No tests were added to the platform as we have separate cards to perform all Cypress tests on the platform.

2024-09-24 13:08 UTC, danigargar requested changes
Rename this commit:
[tests: tests: updated cypress pacts brand](https://github.com/irontec/ivozprovider/pull/2768/commits/ea49d9693a94c0cc72c1cffefeb6f675a271dbd6)

I suggest mixing this changes with "portal/brand: update cypress fixtures", but at least remove the extra "tests:".

2024-09-24 13:08 UTC, danigargar commented on web/portal/brand/src/entities/Company/Action/Impersonate.tsx
> +  const canImpersonate = !profile?.canImpersonate;
Idem

2024-09-24 13:08 UTC, danigargar commented on web/portal/platform/src/entities/Brand/Action/Impersonate.tsx
> +  const canImpersonate = !profile?.canImpersonate;
Idem

2024-09-30 06:06 UTC, danigargar approved these changes

2024-10-01 13:07 UTC, danigargar approved these changes

2024-10-03 16:23 UTC, danigargar requested changes
Please, if possible, add a test for an administrator who can not impersonate.

2024-10-03 16:23 UTC, danigargar commented on web/portal/brand/src/entities/Administrator/Action/Impersonate.tsx
> +          </>
```suggestion
          <Tooltip
            title={_('Impersonate')}
            placement='bottom-start'
            enterTouchDelay={0}
          >
            <span>
              <StyledTableRowCustomCta disabled={true}>
                <AdminPanelSettingsIcon />
              </StyledTableRowCustomCta>
            </span>
          </Tooltip>
```

...or you will end with <> twice.

2024-10-03 16:23 UTC, danigargar commented on web/portal/brand/src/entities/Company/Action/Impersonate.tsx
> +          </>
Idem

2024-10-03 16:23 UTC, danigargar commented on web/portal/platform/src/entities/Administrator/Action/Impersonate.tsx
> +          </>
Idem

2024-10-03 16:23 UTC, danigargar commented on web/portal/platform/src/entities/Brand/Action/Impersonate.tsx
> +          </>
idem

2024-10-03 16:23 UTC, danigargar commented on web/portal/brand/cypress/e2e/Clients/VirtualPbxs/VirtualPbxs.cy.js
> +    }).as('getAdministrator-1');
Why getAdministrator-1? 
It's a VPbx client (or company), not an admin.

2024-10-08 06:15 UTC, danigargar approved these changes

2024-10-08 15:31 UTC, danigargar approved these changes

2024-10-08 15:38 UTC, merged