Add entity application server sets
irontec/ivozprovider pull request #2784
Opened 2024-10-01 12:32 UTC by danigargar

#### Type Of Change 
- [ ] Small bug fix
- [x] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [x] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [x] Commits are split per component (schema, portal/platform, kamusers, agis, ..)
- [x] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 
- [ ] Upport from existing Pull request #XXXX

#### Description

#### Additional information

2024-10-03 09:01 UTC, ironArt3mis requested changes
Functional review required

2024-10-03 09:19 UTC, danigargar commented on library/Ivoz/Provider/Domain/Service/ApplicationServerSet/UpdateProtection.php
He tenido que meter esta comprobación en lifecycle porque el id de la entidad por defecto es cero.
ivoz-core está del todo preparado para estos cero (hay guardas con !$id). El lifecycle no salta si solo se han añadido applicationServers ya que no es un campo propio en base de datos sino una relación.
El sanitize sí salta y es imposible determinar si la entidad ha mutado o no.

2024-10-04 08:28 UTC, rbatistadev commented on web/portal/platform/cypress/fixtures/ApplicationServer/getCollection.json
> +  ]
```suggestion
  ],
  "headers": {
    "x-first-page": "/api/platform/application_servers?_page=1",
    "x-last-page": "/api/platform/application_servers?_page=1",
    "x-next-page": "/api/platform/application_server?_page=1",
    "x-total-items": "3",
    "x-total-pages": "1"
  }
```

2024-10-04 08:32 UTC, rbatistadev approved these changes

2024-10-08 16:00 UTC, ironArt3mis approved these changes

2024-10-08 16:00 UTC, merged