Hide brand price profiles
irontec/ivozprovider pull request #2792
Opened 2024-10-15 16:43 UTC by R0MANDEV

#### Type Of Change 
- [x] Small bug fix
- [x] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [x] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [x] Commits are split per component (schema, portal/platform, kamusers, agis, ..)
- [x] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 
- [ ] Upport from existing Pull request #XXXX

#### Description

#### Additional information

2024-10-15 16:56 UTC, ironArt3mis requested changes
Functional review required

2024-10-16 06:27 UTC, rbatistadev approved these changes

2024-10-16 06:31 UTC, rbatistadev commented
I can't see the logic indicating that "if a brand doesn't have tariff..., I cannot show it on the list"

2024-10-17 07:23 UTC, rbatistadev commented on web/portal/brand/src/entities/Company/Company.tsx
> +    routeMapItem.entity.iden === RatingProfile.iden
```suggestion
    isRatingProfile
```

2024-10-17 07:24 UTC, rbatistadev commented on web/portal/brand/src/entities/Company/Company.tsx
> +    if (!companyFeatures?.includes('billing')) {
```suggestion
    if (!containsBillingFeature) {
```

2024-10-25 06:40 UTC, Kaian approved these changes

2024-10-28 17:14 UTC, ironArt3mis approved these changes

2024-10-28 17:19 UTC, merged