Download multiple recording files
irontec/ivozprovider pull request #2796
Opened 2024-10-23 08:45 UTC by rbatistadev

#### Type Of Change 
- [ ] Small bug fix
- [X] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [X] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [X] Commits are split per component (schema, portal/platform, kamusers, agis, ..)
- [X] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 
- [ ] Upport from existing Pull request #XXXX

#### Description
Multiple recording file download for portal user and client

#### Additional information

2024-10-23 09:30 UTC, danigargar requested changes
Failed pipeline

2024-10-23 11:16 UTC, ironArt3mis requested changes
Functional review required

2024-10-23 13:59 UTC, danigargar requested changes

2024-10-23 13:59 UTC, danigargar commented on web/portal/client/src/translations/es.json
> +  "Download recordings": "Descargar grabaciiones",
Typo! (grabaciiones)

2024-10-28 07:10 UTC, danigargar approved these changes

2024-10-30 15:41 UTC, ironArt3mis approved these changes

2024-10-30 15:52 UTC, ironArt3mis approved these changes

2024-10-30 16:02 UTC, ironArt3mis approved these changes

2024-10-30 17:19 UTC, merged