portal/brand: Residential customers should not have the Residential C…
irontec/ivozprovider pull request #2822
Opened 2024-11-18 21:24 UTC by R0MANDEV

…ustomers option

#### Type Of Change 
- [x] Small bug fix
- [x] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [x] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [x] Commits are split per component (schema, portal/platform, kamusers, agis, ..)
- [x] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 
- [ ] Upport from existing Pull request #XXXX

#### Description

#### Additional information

2024-11-18 21:32 UTC, ironArt3mis requested changes
Functional review required

2024-11-19 07:06 UTC, danigargar requested changes

2024-11-19 07:06 UTC, danigargar commented on web/portal/brand/src/entities/Company/Form.tsx
>      }
For other types of clients, the displayed options are correct. This block does not include code to perform similar filtering for any other account, so I believe this is not the appropriate place to look.

The API request that populates this dropdown is the same across all client creation forms, so the answer likely lies in the frontend.

Have you checked in Features/SelectOptions?

2024-11-19 11:34 UTC, danigargar approved these changes

2024-11-19 11:50 UTC, ironArt3mis approved these changes

2024-11-19 13:27 UTC, merged