Update ChangeLog for 4.3.0 release
irontec/ivozprovider pull request #2825
Opened 2024-11-22 08:48 UTC by Kaian

#### Type Of Change 
- [ ] Small bug fix
- [X] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [X] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [X] Commits are split per component (schema, portal/platform, kamusers, agis, ..)
- [ ] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 
- [ ] Upport from existing Pull request #XXXX

#### Description

Updated documentation with most relevant changes in 4.3.0 release.

> [!NOTE]  
> This PR will be updated with new changes introduced in not yet merged Pull Requests 

#### Additional information

2024-11-22 08:52 UTC, ironArt3mis requested changes
Functional review required

2024-11-22 12:04 UTC, danigargar requested changes

2024-11-22 12:04 UTC, danigargar commented on web/rest/brand/CHANGELOG.md
I don't know whether or not we comment this in the changelog, but application relay set and media relay set are now required fields in insert/update forms for companies of every kind.

2024-11-22 12:04 UTC, danigargar commented on web/rest/platform/CHANGELOG.md
Application server set is a new section in platform/Infrastructure and has platform operators can assign multiple application server sets and media relay set to brands.

2024-11-25 09:03 UTC, Kaian commented on ChangeLog
> +        - Fixed Call CSV Schedulers available fields based on cliend features #2821
Fixed!

2024-11-25 09:04 UTC, Kaian commented on ChangeLog
> +        - Added new API endpoont to retrieve Users API tokens #2817
Fixed!

2024-11-25 09:04 UTC, Kaian commented on web/rest/brand/CHANGELOG.md
Added some entries in Changelog about Media Relay Sets and Application Servers Sets

2024-11-25 09:05 UTC, Kaian commented on web/rest/platform/CHANGELOG.md
Added a new changelog entry for Platform > Infrastructure > Application Server Sets

2024-11-25 13:53 UTC, danigargar approved these changes

2024-12-02 14:56 UTC, cruzccl approved these changes

2024-12-02 14:59 UTC, cruzccl approved these changes

2024-12-02 15:05 UTC, ironArt3mis approved these changes

2024-12-12 08:22 UTC, ironArt3mis approved these changes

2024-12-16 08:10 UTC, ironArt3mis approved these changes

2024-12-16 08:15 UTC, ironArt3mis approved these changes

2024-12-19 11:58 UTC, ironArt3mis approved these changes

2025-01-07 10:08 UTC, ironArt3mis approved these changes

2025-01-08 16:37 UTC, ironArt3mis approved these changes

2025-01-10 08:13 UTC, ironArt3mis approved these changes

2025-01-10 08:57 UTC, ironArt3mis approved these changes

2025-01-13 10:13 UTC, ironArt3mis approved these changes

2025-01-14 15:58 UTC, ironArt3mis approved these changes

2025-01-14 16:09 UTC, ironArt3mis approved these changes

2025-01-14 16:10 UTC, merged