portal/client: New impersonate option in the vPBX client user list
irontec/ivozprovider pull request #2835
Opened 2024-12-10 16:48 UTC by R0MANDEV

#### Type Of Change 
- [ ] Small bug fix
- [x] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [x] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [x] Commits are split per component (schema, portal/platform, kamusers, agis, ..)
- [x] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 
- [ ] Upport from existing Pull request #XXXX

#### Description

#### Additional information

2024-12-17 14:26 UTC, ironArt3mis requested changes
Functional review required

2024-12-17 15:26 UTC, danigargar commented on web/portal/client/src/entities/User/Action/Impersonate.tsx
> +      onClick={(e) => handleClickOpen(e)}
Only vpbx clients have users and capturing click events is not how we use to disable a button. 
Just remove this.

2024-12-18 11:35 UTC, danigargar approved these changes

2024-12-19 08:47 UTC, ironArt3mis approved these changes

2024-12-19 09:03 UTC, merged