Extensions selector do not works fine
irontec/ivozprovider pull request #2848
Opened 2024-12-30 12:44 UTC by rbatistadev

#### Type Of Change 
- [X] Small bug fix
- [ ] New feature or enhancement
- [ ] Breaking change

#### Checklist:
- [X] Commits are named and have tag following [commit rules](https://github.com/irontec/ivozprovider/blob/bleeding/doc/dev/en/commits.md)
- [X] Commits are split per component (schema, portal/platform, kamusers, agis, ..)
- [X] Changes have been tested locally
- [ ] Fixes an existing issue (Fixes #XXXX) 
- [ ] Upport from existing Pull request #XXXX

#### Description

#### Additional information

2025-01-02 09:10 UTC, danigargar requested changes
Some tests are failing

2025-01-02 09:10 UTC, danigargar commented on web/portal/client/src/entities/Extension/Extension.tsx
> +    null: _('Unassigned'),
I have some doubts about this change: it's not requested but it makes sense if you can not possibly get a user extension with null user.

Nothing wrong with your code, but this may suggest a definition error.

2025-01-02 09:26 UTC, rbatistadev commented on web/portal/client/src/entities/Extension/Extension.tsx
> +    null: _('Unassigned'),
In database definition, you can place a user extension but not a user, user is a nullable field with a null default value

2025-01-02 09:50 UTC, danigargar commented on web/portal/client/src/entities/Extension/Extension.tsx
> +    null: _('Unassigned'),
I know that. My concerns are:
·  Should an extension with unassigned type be assignable to an user?
· You can actually add extensions of type user without user using the mass importer.

I'm just pointing the issue may need some clarification. 
I'll approve it as soon as all test are green.

2025-01-02 12:54 UTC, ironArt3mis requested changes
Functional review required

2025-01-03 07:08 UTC, danigargar approved these changes

2025-01-03 07:09 UTC, danigargar approved these changes

2025-01-09 10:18 UTC, danigargar requested changes

2025-01-10 08:59 UTC, danigargar approved these changes

2025-01-13 15:13 UTC, ironArt3mis approved these changes

2025-01-13 15:15 UTC, merged